import { createContext, useContext, useState, useEffect, ReactNode } from 'react';
import { digitalLibraryTranslations } from '@/i18n/digitalLibraryTranslations';

export type Language = 'fr' | 'ar' | 'amz' | 'en' | 'es';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  isRTL: boolean;
}

const translations = {
  fr: {
    // Header
    'header.title': 'Bibliothèque Nationale du Royaume du Maroc',
    'header.home': 'Accueil',
    'header.catalog': 'Catalogue',
    'header.collections': 'Collections Numériques',
    'header.services': 'Services',
    'header.heritage': 'Patrimoine',
    'header.contact': 'Contact',
    'header.search': 'Rechercher dans le catalogue...',
    'header.searchMobile': 'Rechercher...',
    
    // Navigation
    'nav.discover': 'Découvrir la Bibliothèque',
    'nav.services': 'Accéder à nos services',
    'nav.explore': 'Explorer le patrimoine',
    'nav.practical.info': 'Informations pratiques',
    'nav.history.missions': 'Histoire et missions',
    'nav.inscription.access': 'Inscription et accès',
    'nav.specialized.services': 'Services spécialisés',
    'nav.collections': 'Collections',
    'nav.exhibitions.events': 'Expositions et événements',
    'nav.publications': 'Publications',
    'nav.schedules.access': 'Horaires et accès',
    'nav.services.catalog': 'Catalogue de services et tarifs',
    'nav.virtual.tours': 'Visites virtuelles',
    'nav.donors': 'Nos donateurs',
    'nav.library.history': 'Histoire de la bibliothèque',
    'nav.management.message': 'Mot de la Direction',
    'nav.organization.chart': 'Organigramme',
    'nav.login': 'Connexion',
    'nav.dashboard': 'Tableau de bord',
    
    // Additional navigation and menus
    'nav.legal.deposit': 'Dépôt légal',
    'nav.reproduction.request': 'Demande de reproduction',
    'nav.restoration.request': 'Demande de restauration',
    'nav.online.registration': 'Inscription en ligne / réinscription',
    'nav.consult.national.library': 'Consulter la Bibliothèque Nationale',
    'nav.reserve.book': 'Réserver un document',
    'nav.reserve.spaces': 'Réserver nos espaces',
    'nav.specialized.collections': 'Collections spécialisées',
    'nav.digitized.collections': 'Collections numérisées',
    'nav.donated.collections': 'Collections offertes',
    'nav.manuscripts': 'Manuscrits',
    'nav.monographs': 'Monographies',
    
    // Tabs and interface elements
    'tabs.services': 'Services',
    'tabs.parameters': 'Paramètres',
    'tabs.tariffs': 'Tarifs Paramétrables',
    'tabs.history': 'Historique',
    'tabs.logs': 'Historique',
    'tabs.settings': 'Paramètres',
    
    // News and Culture menus
    'nav.consult.news': 'Consulter nos actualités',
    'nav.collaborate': 'Collaborer avec nous',
    'nav.news.section': 'Actualités',
    'nav.culture.section': 'Culture',
    'nav.news.publications': 'Actualités et publications',
    'nav.news.publications.desc': 'Nouvelles acquisitions, actualités du fonds',
    'nav.they.talk.about.us': 'Ils parlent de nous',
    'nav.they.talk.about.us.desc': 'Revue de presse et mentions',
    'nav.cultural.programming': 'Notre programmation culturelle',
    'nav.cultural.programming.desc': 'Agenda, expositions',
    'nav.national.collaborations': 'Collaborations nationales',
    'nav.national.collaborations.desc': 'Partenariats avec les institutions marocaines',
    'nav.international.collaborations': 'Collaborations internationales',
    'nav.international.collaborations.desc': 'Échanges et coopération internationale',
    
    // Hero
    'hero.title': 'Gardienne du Patrimoine Écrit Marocain',
    'hero.subtitle': 'Découvrez les trésors documentaires du Royaume à travers nos collections de manuscrits anciens, livres rares et ressources numériques d\'exception.',
    'hero.exploreBtn': 'Explorer le Catalogue',
    'hero.digitaBtn': 'Collections Numériques',
    
    // Services
    'services.title': 'Nos Services',
    'services.subtitle': 'Des services d\'excellence pour chercheurs, étudiants et passionnés du patrimoine marocain',
    'services.consultation.title': 'Consultation sur Place',
    'services.consultation.desc': 'Accédez à nos collections dans nos salles de lecture spécialisées avec l\'accompagnement de nos experts.',
    'services.digitization.title': 'Numérisation',
    'services.digitization.desc': 'Préservation et accessibilité du patrimoine à travers nos programmes de numérisation de haute qualité.',
    'services.research.title': 'Aide à la Recherche',
    'services.research.desc': 'Bénéficiez de l\'expertise de nos bibliothécaires pour vos recherches académiques et scientifiques.',
    'services.legal.title': 'Dépôt Légal',
    'services.legal.desc': 'Service officiel de collecte et conservation de la production éditoriale nationale.',
    'services.training.title': 'Formation',
    'services.training.desc': 'Programmes de formation en sciences de l\'information et préservation du patrimoine.',
    'services.exhibitions.title': 'Expositions',
    'services.exhibitions.desc': 'Découvrez nos expositions temporaires et permanentes valorisant notre patrimoine.',
    
    // Collections
    'collections.title': 'Collections Numériques',
    'collections.subtitle': 'Explorez notre patrimoine numérisé accessible en ligne',
    'collections.manuscripts.title': 'Manuscrits Anciens',
    'collections.manuscripts.count': '15,000+ manuscrits',
    'collections.manuscripts.desc': 'Collection exceptionnelle de manuscrits arabes, amazighes et hébraïques du Moyen Âge à l\'époque moderne.',
    'collections.rare.title': 'Livres Rares',
    'collections.rare.count': '25,000+ ouvrages',
    'collections.rare.desc': 'Éditions princeps, incunables et ouvrages précieux de la littérature maghrébine et orientale.',
    'collections.maps.title': 'Cartes Historiques',
    'collections.maps.count': '3,500+ cartes',
    'collections.maps.desc': 'Cartographie historique du Maroc et de l\'Afrique du Nord du XVe au XXe siècle.',
    'collections.periodicals.title': 'Périodiques',
    'collections.periodicals.count': '12,000+ titres',
    'collections.periodicals.desc': 'Presse et revues marocaines et maghrébines depuis le XIXe siècle.',
    
    // Footer
    'footer.quickLinks': 'Liens Rapides',
    'footer.services': 'Services',
    'footer.collections': 'Collections',
    'footer.about': 'À Propos',
    'footer.contact': 'Contact',
    'footer.hours': 'Horaires',
    'footer.location': 'Avenue Ibn Battuta, Rabat',
    'footer.phone': 'Téléphone',
    'footer.email': 'Email',
    'footer.social': 'Réseaux Sociaux',
    'footer.rights': 'Tous droits réservés.',
    'footer.monday': 'Lundi - Vendredi: 8h30 - 16h30',
    'footer.saturday': 'Samedi: 8h30 - 12h30',
    'footer.sunday': 'Dimanche: Fermé',

    // BNRM Administration
    'bnrm.backoffice.title': 'Back Office BNRM',
    'bnrm.backoffice.subtitle': 'Gestion centralisée des services de la Bibliothèque Nationale',
    'bnrm.dashboard.tab': 'Tableau de Bord',
    'bnrm.services.tab': 'Services',
    'bnrm.requests.tab': 'Demandes',
    'bnrm.workflow.tab': 'Workflows',
    'bnrm.tariffs.tab': 'Tarifs',
    'bnrm.parameters.tab': 'Paramètres',
    'bnrm.history.tab': 'Historique',
    'bnrm.reports.tab': 'Rapports',
    'bnrm.publicPortal.btn': 'Portail Public',
    'bnrm.back.btn': 'Retour',
    'bnrm.reports.btn': 'Rapports',

    // BNRM Services
    'bnrm.services.title': 'Services BNRM',
    'bnrm.services.description': 'Gestion des services de la Bibliothèque Nationale selon la Loi 67-99',
    'bnrm.services.add': 'Ajouter un Service',
    'bnrm.services.code': 'Code Service',
    'bnrm.services.name': 'Nom du Service',
    'bnrm.services.description.field': 'Description',
    'bnrm.services.category': 'Catégorie',
    'bnrm.services.legal.reference': 'Référence Légale',
    'bnrm.services.actions': 'Actions',
    'bnrm.services.edit': 'Modifier',
    'bnrm.services.delete': 'Supprimer',

    // BNRM Tariffs
    'bnrm.tariffs.title': 'Tarifs Paramétrables',
    'bnrm.tariffs.description': 'Gestion des tarifs avec historisation automatique',
    'bnrm.tariffs.code': 'Code Tarif',
    'bnrm.tariffs.service': 'Service',
    'bnrm.tariffs.amount': 'Montant',
    'bnrm.tariffs.currency': 'Devise',
    'bnrm.tariffs.condition': 'Condition',
    'bnrm.tariffs.validity': 'Période de Validité',
    'bnrm.tariffs.status': 'Statut',
    'bnrm.tariffs.active': 'Actif',
    'bnrm.tariffs.inactive': 'Inactif',

    // BNRM Parameters
    'bnrm.parameters.title': 'Paramètres Système',
    'bnrm.parameters.description': 'Configuration des paramètres opérationnels',
    'bnrm.parameters.key': 'Clé',
    'bnrm.parameters.value': 'Valeur',
    'bnrm.parameters.description.field': 'Description',
    'bnrm.parameters.lastUpdate': 'Dernière Mise à Jour',

    // BNRM Workflow
    'bnrm.workflow.title': 'Gestion des Workflows',
    'bnrm.workflow.description': 'Configuration et suivi des processus métier',
    'bnrm.workflow.name': 'Nom du Workflow',
    'bnrm.workflow.steps': 'Étapes',
    'bnrm.workflow.create': 'Créer un Workflow',
    'bnrm.workflow.edit': 'Modifier le Workflow',
    'bnrm.workflow.delete': 'Supprimer',
    'bnrm.workflow.activate': 'Activer',
    'bnrm.workflow.deactivate': 'Désactiver',
    'bnrm.workflow.confirmDelete': 'Êtes-vous sûr de vouloir supprimer ce workflow ?',
    'bnrm.workflow.confirmActivate': 'Êtes-vous sûr de vouloir activer ce workflow ?',
    'bnrm.workflow.confirmDeactivate': 'Êtes-vous sûr de vouloir désactiver ce workflow ?',

    // Legal Deposit
    'legal.deposit.title': 'Gestion du Dépôt Légal',
    'legal.deposit.subtitle': 'Administration du dépôt légal selon la législation marocaine',
    'legal.deposit.declarations': 'Déclarations',
    'legal.deposit.archiving': 'Archivage',
    'legal.deposit.reports': 'Rapports',

    // Admin Settings
    'admin.settings.title': 'Paramètres d\'Administration',
    'admin.settings.subtitle': 'Configuration et gestion du système',
    'admin.permissions.title': 'Gestion des Droits et Permissions',
    'admin.permissions.description': 'Contrôler l\'accès aux fonctionnalités',
    'admin.content.title': 'Gestion de contenu',
    'admin.content.description': 'Gérer les contenus et publications',
    'admin.users.title': 'Gestion des Utilisateurs',
    'admin.users.description': 'Administration des comptes utilisateurs',
    'admin.activity.title': 'Surveillance d\'Activité',
    'admin.activity.description': 'Monitoring et logs système',
    'admin.archiving.title': 'Gestion de l\'Archivage',
    'admin.archiving.description': 'Configuration des politiques d\'archivage',
    'admin.legal.deposit.title': 'Dépôt Légal',
    'admin.legal.deposit.description': 'Administration du dépôt légal',
    'admin.subscriptions.title': 'Gestion des Abonnements',
    'admin.subscriptions.description': 'Plans et abonnements utilisateurs',
    'admin.bnrm.tariffs.title': 'Gestion des Tarifs BNRM',
    'admin.bnrm.tariffs.description': 'Gérer les tarifs et services de la BNRM',
    'admin.bnrm.backoffice.title': 'Back Office BNRM',
    'admin.bnrm.backoffice.description': 'Interface d\'administration BNRM',
    'admin.workflow.title': 'Gestion des Workflows',
    'admin.workflow.description': 'Configuration des processus métier',

    // Common Actions
    'common.save': 'Enregistrer',
    'common.cancel': 'Annuler',
    'common.edit': 'Modifier',
    'common.delete': 'Supprimer',
    'common.add': 'Ajouter',
    'common.confirm': 'Confirmer',
    'common.close': 'Fermer',
    'common.loading': 'Chargement...',
    'common.error': 'Erreur',
    'common.success': 'Succès',
    'common.warning': 'Attention',
    'common.yes': 'Oui',
    'common.no': 'Non',
    'common.search': 'Rechercher',
    'common.filter': 'Filtrer',
    'common.export': 'Exporter',
    'common.import': 'Importer',
    'common.view': 'Voir',
    'common.download': 'Télécharger'
  },
  ar: {
    // Header
    'header.title': 'المكتبة الوطنية للمملكة المغربية',
    'header.home': 'الرئيسية',
    'header.catalog': 'الفهرس',
    'header.collections': 'المجموعات الرقمية',
    'header.services': 'الخدمات',
    'header.heritage': 'التراث',
    'header.contact': 'اتصل بنا',
    'header.search': 'البحث في الفهرس...',
    'header.searchMobile': 'بحث...',
    
    // Navigation
    'nav.discover': 'اكتشف المكتبة',
    'nav.services': 'الوصول إلى خدماتنا',
    'nav.explore': 'استكشاف التراث',
    'nav.practical.info': 'معلومات عملية',
    'nav.history.missions': 'التاريخ والمهام',
    'nav.inscription.access': 'التسجيل والوصول',
    'nav.specialized.services': 'خدمات متخصصة',
    'nav.collections': 'المجموعات',
    'nav.exhibitions.events': 'المعارض والأحداث',
    'nav.publications': 'المنشورات',
    'nav.schedules.access': 'المواعيد والوصول',
    'nav.services.catalog': 'كتالوج الخدمات والتعريفات',
    'nav.virtual.tours': 'جولات افتراضية',
    'nav.donors': 'المتبرعون',
    'nav.library.history': 'تاريخ المكتبة',
    'nav.management.message': 'كلمة الإدارة',
    'nav.organization.chart': 'الهيكل التنظيمي',
    'nav.login': 'تسجيل الدخول',
    'nav.dashboard': 'لوحة التحكم',
    
    // Additional navigation and menus
    'nav.legal.deposit': 'الإيداع القانوني',
    'nav.reproduction.request': 'طلب الاستنساخ',
    'nav.restoration.request': 'طلب الترميم',
    'nav.online.registration': 'التسجيل عبر الإنترنت / إعادة التسجيل',
    'nav.consult.national.library': 'استشارة المكتبة الوطنية',
    'nav.reserve.book': 'حجز كتاب',
    'nav.reserve.spaces': 'حجز المساحات',
    'nav.specialized.collections': 'المجموعات المتخصصة',
    'nav.digitized.collections': 'المجموعات الرقمية',
    'nav.donated.collections': 'المجموعات المهداة',
    'nav.manuscripts': 'المخطوطات',
    'nav.monographs': 'المونوغرافيات',
    
    // Tabs and interface elements
    'tabs.services': 'الخدمات',
    'tabs.parameters': 'المعاملات',
    'tabs.tariffs': 'التعريفات القابلة للتعديل',
    'tabs.history': 'السجل',
    'tabs.logs': 'السجل',
    'tabs.settings': 'الإعدادات',
    
    // News and Culture menus
    'nav.consult.news': 'استشر أخبارنا',
    'nav.collaborate': 'تعاون معنا',
    'nav.news.section': 'الأخبار',
    'nav.culture.section': 'الثقافة',
    'nav.news.publications': 'الأخبار والمنشورات',
    'nav.news.publications.desc': 'المقتنيات الجديدة، أخبار المجموعة',
    'nav.they.talk.about.us': 'يتحدثون عنا',
    'nav.they.talk.about.us.desc': 'مراجعة الصحافة والإشارات',
    'nav.cultural.programming': 'برنامجنا الثقافي',
    'nav.cultural.programming.desc': 'الأجندة، المعارض',
    'nav.national.collaborations': 'التعاون الوطني',
    'nav.national.collaborations.desc': 'شراكات مع المؤسسات المغربية',
    'nav.international.collaborations': 'التعاون الدولي',
    'nav.international.collaborations.desc': 'التبادلات والتعاون الدولي',
    
    // Hero
    'hero.title': 'حارسة التراث المكتوب المغربي',
    'hero.subtitle': 'اكتشف كنوز المملكة الوثائقية من خلال مجموعاتنا من المخطوطات القديمة والكتب النادرة والموارد الرقمية الاستثنائية.',
    'hero.exploreBtn': 'استكشف الفهرس',
    'hero.digitaBtn': 'المجموعات الرقمية',
    
    // Services
    'services.title': 'خدماتنا',
    'services.subtitle': 'خدمات متميزة للباحثين والطلاب وعشاق التراث المغربي',
    'services.consultation.title': 'الاطلاع في المكان',
    'services.consultation.desc': 'الوصول إلى مجموعاتنا في قاعات القراءة المتخصصة مع مرافقة خبرائنا.',
    'services.digitization.title': 'الرقمنة',
    'services.digitization.desc': 'حفظ وإتاحة التراث من خلال برامج الرقمنة عالية الجودة.',
    'services.research.title': 'المساعدة في البحث',
    'services.research.desc': 'استفد من خبرة أمناء المكتبات لبحوثك الأكاديمية والعلمية.',
    'services.legal.title': 'الإيداع القانوني',
    'services.legal.desc': 'الخدمة الرسمية لجمع وحفظ الإنتاج التحريري الوطني.',
    'services.training.title': 'التكوين',
    'services.training.desc': 'برامج التكوين في علوم المعلومات وحفظ التراث.',
    'services.exhibitions.title': 'المعارض',
    'services.exhibitions.desc': 'اكتشف معارضنا المؤقتة والدائمة التي تعرض تراثنا.',
    
    // Collections
    'collections.title': 'المجموعات الرقمية',
    'collections.subtitle': 'استكشف تراثنا المرقمن المتاح عبر الإنترنت',
    'collections.manuscripts.title': 'المخطوطات القديمة',
    'collections.manuscripts.count': '+15,000 مخطوطة',
    'collections.manuscripts.desc': 'مجموعة استثنائية من المخطوطات العربية والأمازيغية والعبرية من العصور الوسطى إلى العصر الحديث.',
    'collections.rare.title': 'الكتب النادرة',
    'collections.rare.count': '+25,000 مؤلف',
    'collections.rare.desc': 'الطبعات الأولى والكتب القيمة من الأدب المغاربي والشرقي.',
    'collections.maps.title': 'الخرائط التاريخية',
    'collections.maps.count': '+3,500 خريطة',
    'collections.maps.desc': 'الخرائط التاريخية للمغرب وشمال أفريقيا من القرن الخامس عشر إلى القرن العشرين.',
    'collections.periodicals.title': 'الدوريات',
    'collections.periodicals.count': '+12,000 عنوان',
    'collections.periodicals.desc': 'الصحافة والمجلات المغربية والمغاربية منذ القرن التاسع عشر.',
    
    // Footer
    'footer.quickLinks': 'روابط سريعة',
    'footer.services': 'الخدمات',
    'footer.collections': 'المجموعات',
    'footer.about': 'حول',
    'footer.contact': 'اتصل بنا',
    'footer.hours': 'المواعيد',
    'footer.location': 'شارع ابن بطوطة، الرباط',
    'footer.phone': 'الهاتف',
    'footer.email': 'البريد الإلكتروني',
    'footer.social': 'وسائل التواصل',
    'footer.rights': 'جميع الحقوق محفوظة.',
    'footer.monday': 'الاثنين - الجمعة: 8:30 - 16:30',
    'footer.saturday': 'السبت: 8:30 - 12:30',
    'footer.sunday': 'الأحد: مغلق',

    // BNRM Administration
    'bnrm.backoffice.title': 'المكتب الخلفي للمكتبة الوطنية',
    'bnrm.backoffice.subtitle': 'الإدارة المركزية لخدمات المكتبة الوطنية',
    'bnrm.dashboard.tab': 'لوحة التحكم',
    'bnrm.services.tab': 'الخدمات',
    'bnrm.requests.tab': 'الطلبات',
    'bnrm.workflow.tab': 'سير العمل',
    'bnrm.tariffs.tab': 'التعريفات',
    'bnrm.parameters.tab': 'المعاملات',
    'bnrm.history.tab': 'السجل',
    'bnrm.reports.tab': 'التقارير',
    'bnrm.publicPortal.btn': 'البوابة العامة',
    'bnrm.back.btn': 'العودة',
    'bnrm.reports.btn': 'التقارير',

    // BNRM Services
    'bnrm.services.title': 'خدمات المكتبة الوطنية',
    'bnrm.services.description': 'إدارة خدمات المكتبة الوطنية وفقاً للقانون 67-99',
    'bnrm.services.add': 'إضافة خدمة',
    'bnrm.services.code': 'رمز الخدمة',
    'bnrm.services.name': 'اسم الخدمة',
    'bnrm.services.description.field': 'الوصف',
    'bnrm.services.category': 'الفئة',
    'bnrm.services.legal.reference': 'المرجع القانوني',
    'bnrm.services.actions': 'الإجراءات',
    'bnrm.services.edit': 'تعديل',
    'bnrm.services.delete': 'حذف',

    // BNRM Tariffs
    'bnrm.tariffs.title': 'التعريفات القابلة للتعديل',
    'bnrm.tariffs.description': 'إدارة التعريفات مع الأرشفة التلقائية',
    'bnrm.tariffs.code': 'رمز التعريفة',
    'bnrm.tariffs.service': 'الخدمة',
    'bnrm.tariffs.amount': 'المبلغ',
    'bnrm.tariffs.currency': 'العملة',
    'bnrm.tariffs.condition': 'الشرط',
    'bnrm.tariffs.validity': 'فترة الصلاحية',
    'bnrm.tariffs.status': 'الحالة',
    'bnrm.tariffs.active': 'نشط',
    'bnrm.tariffs.inactive': 'غير نشط',

    // BNRM Parameters
    'bnrm.parameters.title': 'معاملات النظام',
    'bnrm.parameters.description': 'تكوين المعاملات التشغيلية',
    'bnrm.parameters.key': 'المفتاح',
    'bnrm.parameters.value': 'القيمة',
    'bnrm.parameters.description.field': 'الوصف',
    'bnrm.parameters.lastUpdate': 'آخر تحديث',

    // BNRM Workflow
    'bnrm.workflow.title': 'إدارة سير العمل',
    'bnrm.workflow.description': 'تكوين ومتابعة عمليات الأعمال',
    'bnrm.workflow.name': 'اسم سير العمل',
    'bnrm.workflow.steps': 'الخطوات',
    'bnrm.workflow.create': 'إنشاء سير عمل',
    'bnrm.workflow.edit': 'تعديل سير العمل',
    'bnrm.workflow.delete': 'حذف',
    'bnrm.workflow.activate': 'تفعيل',
    'bnrm.workflow.deactivate': 'إلغاء التفعيل',
    'bnrm.workflow.confirmDelete': 'هل أنت متأكد من حذف سير العمل هذا؟',
    'bnrm.workflow.confirmActivate': 'هل أنت متأكد من تفعيل سير العمل هذا؟',
    'bnrm.workflow.confirmDeactivate': 'هل أنت متأكد من إلغاء تفعيل سير العمل هذا؟',

    // Legal Deposit
    'legal.deposit.title': 'إدارة الإيداع القانوني',
    'legal.deposit.subtitle': 'إدارة الإيداع القانوني وفقاً للتشريع المغربي',
    'legal.deposit.declarations': 'التصريحات',
    'legal.deposit.archiving': 'الأرشفة',
    'legal.deposit.reports': 'التقارير',

    // Admin Settings
    'admin.settings.title': 'إعدادات الإدارة',
    'admin.settings.subtitle': 'تكوين وإدارة النظام',
    'admin.permissions.title': 'إدارة الحقوق والصلاحيات',
    'admin.permissions.description': 'التحكم في الوصول للوظائف',
    'admin.content.title': 'إدارة المحتوى',
    'admin.content.description': 'إدارة المحتويات والمنشورات',
    'admin.users.title': 'إدارة المستخدمين',
    'admin.users.description': 'إدارة حسابات المستخدمين',
    'admin.activity.title': 'مراقبة النشاط',
    'admin.activity.description': 'المراقبة وسجلات النظام',
    'admin.archiving.title': 'إدارة الأرشفة',
    'admin.archiving.description': 'تكوين سياسات الأرشفة',
    'admin.legal.deposit.title': 'الإيداع القانوني',
    'admin.legal.deposit.description': 'إدارة الإيداع القانوني',
    'admin.subscriptions.title': 'إدارة الاشتراكات',
    'admin.subscriptions.description': 'خطط واشتراكات المستخدمين',
    'admin.bnrm.tariffs.title': 'إدارة تعريفات المكتبة الوطنية',
    'admin.bnrm.tariffs.description': 'إدارة تعريفات وخدمات المكتبة الوطنية',
    'admin.bnrm.backoffice.title': 'المكتب الخلفي للمكتبة الوطنية',
    'admin.bnrm.backoffice.description': 'واجهة إدارة المكتبة الوطنية',
    'admin.workflow.title': 'إدارة سير العمل',
    'admin.workflow.description': 'تكوين عمليات الأعمال',

    // Common Actions
    'common.save': 'حفظ',
    'common.cancel': 'إلغاء',
    'common.edit': 'تعديل',
    'common.delete': 'حذف',
    'common.add': 'إضافة',
    'common.confirm': 'تأكيد',
    'common.close': 'إغلاق',
    'common.loading': 'جاري التحميل...',
    'common.error': 'خطأ',
    'common.success': 'نجح',
    'common.warning': 'تحذير',
    'common.yes': 'نعم',
    'common.no': 'لا',
    'common.search': 'بحث',
    'common.filter': 'تصفية',
    'common.export': 'تصدير',
    'common.import': 'استيراد',
    'common.view': 'عرض',
    'common.download': 'تحميل'
  },
  amz: {
    // Header (Tifinagh)
    'header.title': 'ⵜⴰⵙⴷⴰⵡⵉⵜ ⵜⴰⵏⴰⵎⵓⵔⵜ ⵏ ⵓⴳⵍⴷⵓⵏ ⵏ ⵍⵎⵖⵔⵉⴱ',
    'header.home': 'ⴰⵙⵏⵓⴱⴳ',
    'header.catalog': 'ⴰⵎⴳⵔⴰⴷ',
    'header.collections': 'ⵜⵉⵙⵎⴰⵍⵉⵏ ⵜⵉⵎⵣⵣⵢⵏⵉⵏ',
    'header.services': 'ⵜⴰⵏⴰⵏⵜⵉⵏ',
    'header.heritage': 'ⴰⵎⵓⵔ',
    'header.contact': 'ⴰⵎⵢⴰⵡⴰⴹ',
    'header.search': 'ⴰⵔⵣⵣⵓ ⴳ ⵓⵎⴳⵔⴰⴷ...',
    'header.searchMobile': 'ⴰⵔⵣⵣⵓ...',
    
    // Navigation
    'nav.discover': 'ⴰⴼ ⵜⵙⴷⴰⵡⵉⵜ',
    'nav.services': 'ⴰⴽⵛⵛⵓⵎ ⵖⵔ ⵜⵏⴰⵏⵜⵉⵏ ⵏⵏⵖ',
    'nav.explore': 'ⵙⵙⴽⵛⴼ ⴰⵎⵓⵔ',
    'nav.practical.info': 'ⵉⵏⵖⵎⵉⵙⵏ ⵉⵎⴰⵔⵙⵏ',
    'nav.history.missions': 'ⴰⵎⵣⵔⵓⵢ ⴷ ⵜⵙⵀⵍⵓⵜⵉⵏ',
    'nav.inscription.access': 'ⴰⵙⵎⵓⵍ ⴷ ⵓⴽⵛⵛⵓⵎ',
    'nav.specialized.services': 'ⵜⵏⴰⵏⵜⵉⵏ ⵜⵉⴳⵣⵣⵓⵎⵉⵏ',
    'nav.collections': 'ⵜⵉⵙⵎⴰⵍⵉⵏ',
    'nav.exhibitions.events': 'ⵉⵙⵎⴰⵍⵏ ⴷ ⵜⵎⴰⵀⵍⵉⵏ',
    'nav.publications': 'ⵜⵓⴼⴼⵖⵉⵏ',
    'nav.schedules.access': 'ⴰⴽⵓⴷ ⴷ ⵓⴽⵛⵛⵓⵎ',
    'nav.services.catalog': 'ⴰⵎⴳⵔⴰⴷ ⵏ ⵜⵏⴰⵏⵜⵉⵏ ⴷ ⵉⵎⵍⴰⵙⵏ',
    'nav.virtual.tours': 'ⵜⵓⵏⵖⵉⵍⵉⵏ ⵜⵉⵡⵀⵎⵉⵏ',
    'nav.donors': 'ⵉⵎⴼⴽⴰⵏ ⵏⵏⵖ',
    'nav.library.history': 'ⴰⵎⵣⵔⵓⵢ ⵏ ⵜⵙⴷⴰⵡⵉⵜ',
    'nav.management.message': 'ⴰⵡⴰⵍ ⵏ ⵓⵙⴼⵔⵓⴽ',
    'nav.organization.chart': 'ⴰⵙⵍⵖⵓ ⵏ ⵓⵙⴷⵓⵙ',
    'nav.login': 'ⴰⴽⵛⵛⵓⵎ',
    'nav.dashboard': 'ⴰⴼⵍⵍⵉⵙ ⵏ ⵓⵙⴼⵔⵓⴽ',
    
    // Additional navigation and menus
    'nav.legal.deposit': 'ⴰⵙⵔⵙ ⴰⵏⴰⵎⵓⵙ',
    'nav.reproduction.request': 'ⴰⵙⵓⵜⵔ ⵏ ⵓⵙⵏⵓⵍⴼⵓ',
    'nav.restoration.request': 'ⴰⵙⵓⵜⵔ ⵏ ⵓⵙⵎⴷ',
    'nav.online.registration': 'ⴰⵙⵎⵓⵍ ⵙ ⵉⵏⵜⴰⵔⵏⵉⵜ / ⴰⵍⵙ ⵓⵙⵎⵓⵍ',
    'nav.consult.national.library': 'ⴰⵎⵢⴰⵡⴰⴹ ⴰⴽⴷ ⵜⵙⴷⴰⵡⵉⵜ ⵜⴰⵏⴰⵎⵓⵔⵜ',
    'nav.reserve.book': 'ⴰⴽⵙⵉ ⵓⴷⵍⵉⵙ',
    'nav.reserve.spaces': 'ⴰⴽⵙⵉ ⵉⴷⵖⴰⵔⵏ',
    'nav.specialized.collections': 'ⵜⵉⵙⵎⴰⵍⵉⵏ ⵜⵉⴳⵣⵣⵓⵎⵉⵏ',
    'nav.digitized.collections': 'ⵜⵉⵙⵎⴰⵍⵉⵏ ⵜⵉⵎⵣⵣⵢⵏⵉⵏ',
    'nav.donated.collections': 'ⵜⵉⵙⵎⴰⵍⵉⵏ ⵜⵓⴼⴽⵉⵏ',
    'nav.manuscripts': 'ⵉⵔⴰⵜⵏ',
    'nav.monographs': 'ⵉⵎⵓⵏⵓⴳⵔⴰⴼⵏ',
    
    // Tabs and interface elements
    'tabs.services': 'ⵜⵏⴰⵏⵜⵉⵏ',
    'tabs.parameters': 'ⵜⵉⵙⵎⴽⵜⴰ',
    'tabs.tariffs': 'ⵉⵎⵍⴰⵙⵏ ⵉⵜⵜⵓⵙⵏⴼⵍⵏ',
    'tabs.history': 'ⴰⵎⵣⵔⵓⵢ',
    'tabs.logs': 'ⴰⵎⵣⵔⵓⵢ',
    'tabs.settings': 'ⵜⵉⵙⵖⵜⵉⵏ',
    
    // News and Culture menus
    'nav.consult.news': 'ⴰⵏⵏⴰⵢ ⵉⵏⵖⵎⵉⵙⵏ ⵏⵏⵖ',
    'nav.collaborate': 'ⴰⵎⵓⵏ ⴰⴽⴷⵏⵏⵖ',
    'nav.news.section': 'ⵉⵏⵖⵎⵉⵙⵏ',
    'nav.culture.section': 'ⴰⴷⵍⵙⴰⵏ',
    'nav.news.publications': 'ⵉⵏⵖⵎⵉⵙⵏ ⴷ ⵜⵓⴼⴼⵖⵉⵏ',
    'nav.news.publications.desc': 'ⴰⵍⵙ ⵓⵙⵎⵓⵏ, ⵉⵏⵖⵎⵉⵙⵏ ⵏ ⵜⵙⵎⴰⵍⵜ',
    'nav.they.talk.about.us': 'ⴰⵔ ⴰⵖ ⵜⵜⴰⵡⴰⵍⵏ',
    'nav.they.talk.about.us.desc': 'ⴰⵏⵏⴰⵢ ⵏ ⵜⵏⴱⴹⵜ ⴷ ⵜⵇⵇⵏⵉⵏ',
    'nav.cultural.programming': 'ⴰⵀⵔⵓⵙ ⵏⵏⵖ ⴰⴷⵍⵙⴰⵏ',
    'nav.cultural.programming.desc': 'ⴰⵙⵍⴳⵏ, ⵉⵙⵎⴰⵍⵏ',
    'nav.national.collaborations': 'ⴰⵎⵓⵏ ⴰⵏⴰⵎⵓⵔ',
    'nav.national.collaborations.desc': 'ⵜⵎⵢⴰⵡⴰⵙⵉⵏ ⴰⴽⴷ ⵜⵙⵙⴽⵍⵉⵡⵉⵏ ⵜⵉⵎⵖⵔⵉⴱⵉⵢⵉⵏ',
    'nav.international.collaborations': 'ⴰⵎⵓⵏ ⴰⴳⵔⴰⵖⵍⴰⵏ',
    'nav.international.collaborations.desc': 'ⴰⵎⵓⵏ ⴷ ⵜⵎⵢⴰⵡⴰⵙⵜ ⵜⴰⴳⵔⴰⵖⵍⴰⵏⵜ',
    
    // Hero
    'hero.title': 'ⴰⵎⵙⵙⴰⵔ ⵏ ⵓⵎⵓⵔ ⵉⵜⵜⵓⴳⴰⵏ ⴰⵎⵖⵔⵉⴱⵉ',
    'hero.subtitle': 'ⴰⴼ ⵉⵏⴼⴰⵍⵏ ⵏ ⵜⴳⵍⴷⵉⵜ ⴰⵔ ⵜⵙⵎⴰⵍⵉⵏ ⵏⵏⵖ ⵏ ⵉⵔⴰⵜⵏ ⵉⵣⴰⵢⴽⵓⵏⵏ, ⵉⴷⵍⵉⵙⵏ ⵉⵣⴷⴰⵔⵏ ⴷ ⵜⵅⵣⵉⵏⵜ ⵜⴰⵎⵣⵣⵢⴰⵏⵜ ⵜⴰⵛⵜⵓⴽⵜ.',
    'hero.exploreBtn': 'ⵙⵙⴽⵛⴼ ⴰⵎⴳⵔⴰⴷ',
    'hero.digitaBtn': 'ⵜⵉⵙⵎⴰⵍⵉⵏ ⵜⵉⵎⵣⵣⵢⵏⵉⵏ',
    
    // Services
    'services.title': 'ⵜⴰⵏⴰⵏⵜⵉⵏ ⵏⵏⵖ',
    'services.subtitle': 'ⵜⴰⵏⴰⵏⵜⵉⵏ ⵏ ⵜⵊⵊⵓⴳⵜ ⵉ ⵉⵎⵔⵣⴰ, ⵉⵎⵖⴰⵔⵏ ⴷ ⵉⵎⵢⴰⵏⴰⵡⵏ ⵏ ⵓⵎⵓⵔ ⴰⵎⵖⵔⵉⴱⵉ',
    'services.consultation.title': 'ⴰⵖⵔⵉ ⴳ ⵓⴷⵖⴰⵔ',
    'services.consultation.desc': 'ⴰⴽⵛⵛⵓⵎ ⵖⵔ ⵜⵙⵎⴰⵍⵉⵏ ⵏⵏⵖ ⴳ ⵜⵎⵙⴽⵉⵏⵉⵏ ⵏ ⵜⵖⵔⵉ ⵜⵉⴳⵣⵣⵓⵎⵉⵏ ⴰⴽⴷ ⵓⵎⴰⵔⵓ ⵏ ⵉⵎⵓⵙⵏⴰⵡⵏ ⵏⵏⵖ.',
    'services.digitization.title': 'ⴰⵙⵎⵣⵣⵢⴰⵏ',
    'services.digitization.desc': 'ⴰⵃⵟⵟⵓ ⴷ ⵓⴽⵛⵛⵓⵎ ⵏ ⵓⵎⵓⵔ ⵙ ⵉⵀⵔⵓⵙⵏ ⵏ ⵓⵙⵎⵣⵣⵢⴰⵏ ⵏ ⵜⵉⵍⴰⵡⵜ ⵉⵙⵙⵓⵍⵏ.',
    'services.research.title': 'ⵜⴰⵡⵙⵙⴰ ⴳ ⵓⵔⵣⵣⵓ',
    'services.research.desc': 'ⴰⵔⴰⵎ ⵙⴳ ⵜⴰⵡⵙⵙⴰ ⵏ ⵉⵎⵎⴰⵍⴰⵏ ⵏ ⵜⵙⴷⴰⵡⵉⵜ ⵉ ⵉⵔⵣⵣⵓⵜⵏ ⵏⵏⵓⵏ ⵉⵖⵔⵎⴰⵏⵏ ⴷ ⵉⵎⴰⵙⵙⴰⵏⵏ.',
    'services.legal.title': 'ⴰⵙⵔⵙ ⴰⵏⴰⵎⵓⵙ',
    'services.legal.desc': 'ⵜⴰⵏⴰⵏⵜ ⵜⵓⵏⵚⵉⴱⵜ ⵏ ⵓⵙⵎⵓⵏ ⴷ ⵓⵃⵟⵟⵓ ⵏ ⵓⵙⴼⴰⵔⵓ ⴰⵏⴰⵎⵓⵔ ⴰⵏⴰⵎⵓⵔ.',
    'services.training.title': 'ⴰⵙⵎⵓⵏ',
    'services.training.desc': 'ⵉⵀⵔⵓⵙⵏ ⵏ ⵓⵙⵎⵓⵏ ⴳ ⵜⵎⴰⵙⵙⵉⵏ ⵏ ⵜⵓⵍⵍⵉⵙⵉⵏ ⴷ ⵓⵃⵟⵟⵓ ⵏ ⵓⵎⵓⵔ.',
    'services.exhibitions.title': 'ⵉⵙⵎⴰⵍⵏ',
    'services.exhibitions.desc': 'ⴰⴼ ⵉⵙⵎⴰⵍⵏ ⵏⵏⵖ ⵉⴽⵓⴷⴰⵏⵏ ⴷ ⵉⵎⵉⴽⵔⴰⵜⵏ ⴰⴷ ⵉⵣⵎⵔⵏ ⴰⵎⵓⵔ ⵏⵏⵖ.',
    
    // Collections
    'collections.title': 'ⵜⵉⵙⵎⴰⵍⵉⵏ ⵜⵉⵎⵣⵣⵢⵏⵉⵏ',
    'collections.subtitle': 'ⵙⵙⴽⵛⴼ ⴰⵎⵓⵔ ⵏⵏⵖ ⴰⵎⵣⵣⵢⴰⵏ ⴰⴷ ⵉⵏⵏⴰⵛⴽⴰⵎⵏ ⵙⴳ ⵉⵏⵜⴰⵔⵏⵉⵜ',
    'collections.manuscripts.title': 'ⵉⵔⴰⵜⵏ ⵉⵣⴰⵢⴽⵓⵏⵏ',
    'collections.manuscripts.count': '+15,000 ⴰⵔⴰⵜ',
    'collections.manuscripts.desc': 'ⵜⴰⵙⵎⴰⵍⵜ ⵜⴰⵛⵜⵓⴽⵜ ⵏ ⵉⵔⴰⵜⵏ ⵉⵄⴰⵔⴰⴱⵏ, ⵉⵎⴰⵣⵉⵖⵏ ⴷ ⵉⵄⵉⴱⵔⵉⵢⵏ ⵙⴳ ⵓⵣⵎⵣ ⴰⵏⴰⵎⵎⴰⵙ ⴰⵔ ⵓⵣⵎⵣ ⴰⵜⵔⴰⵔ.',
    'collections.rare.title': 'ⵉⴷⵍⵉⵙⵏ ⵉⵣⴷⴰⵔⵏ',
    'collections.rare.count': '+25,000 ⵓⵎⵥⵍⴰⵢ',
    'collections.rare.desc': 'ⵜⵓⵙⵓⵜⵉⵏ ⵜⵉⵎⵣⵡⵓⵔⴰ ⴷ ⵉⴷⵍⵉⵙⵏ ⵉⵔⴰⵎⵏ ⵙⴳ ⵜⵓⵏⴳⵜ ⵜⴰⵎⵖⵔⵉⴱⵉⵢⵜ ⴷ ⵜⴰⵙⵉⵍⴰⵏⵜ.',
    'collections.maps.title': 'ⵜⵏⵇⵇⵉⵛⵉⵏ ⵜⵉⵎⵣⵔⵓⵢⵉⵏ',
    'collections.maps.count': '+3,500 ⵜⴰⵏⵇⵇⵉⵛⵜ',
    'collections.maps.desc': 'ⵜⴰⵏⵇⵇⵉⵛⵜ ⵜⴰⵎⵣⵔⵓⵢⵜ ⵏ ⵍⵎⵖⵔⵉⴱ ⴷ ⵓⴳⴰⴼⴰⵢ ⵏ ⵜⴰⴼⵔⵉⵇⵜ ⵙⴳ ⵜⴰⵙⵓⵜ ⵜⵉⵙ 15 ⴰⵔ ⵜⵉⵙ 20.',
    'collections.periodicals.title': 'ⵜⵓⵙⵓⵜⵉⵏ ⵜⵓⵏⴰⵏⴰⵔⵉⵏ',
    'collections.periodicals.count': '+12,000 ⵓⵣⵡⵍ',
    'collections.periodicals.desc': 'ⵜⴰⵏⴱⴰⴹⵜ ⴷ ⵜⵎⴳⵔⴰⴷⵉⵏ ⵜⵉⵎⵖⵔⵉⴱⵉⵢⵉⵏ ⴷ ⵜⵉⵎⵖⵔⵉⴱⵉⵢⵉⵏ ⵙⴳ ⵜⴰⵙⵓⵜ ⵜⵉⵙ 19.',
    
    // Footer
    'footer.quickLinks': 'ⵉⵣⴷⴰⵢⵏ ⵉⵖⵣⵣⵉⴼⵏ',
    'footer.services': 'ⵜⴰⵏⴰⵏⵜⵉⵏ',
    'footer.collections': 'ⵜⵉⵙⵎⴰⵍⵉⵏ',
    'footer.about': 'ⵖⴼ',
    'footer.contact': 'ⴰⵎⵢⴰⵡⴰⴹ',
    'footer.hours': 'ⴰⴽⵓⴷ',
    'footer.location': 'ⴰⴱⵔⵉⴷ ⵏ ⵉⴱⵏ ⴱⴰⵟⵟⵓⵟⴰ, ⵔⵔⴱⴰⵟ',
    'footer.phone': 'ⴰⵜⵍⵉⴼⵓⵏ',
    'footer.email': 'ⵉⵎⴰⵢⵍ',
    'footer.social': 'ⵉⵣⴷⴰⵢⵏ ⵉⵏⴰⵎⵓⵏⵏ',
    'footer.rights': 'ⴰⴽⴽ ⵉⵣⵔⴼⴰⵏ ⵃⵟⵟⵓⵏ.',
    'footer.monday': 'ⴰⵔⵉⵎ - ⵙⵉⵎⵙ: 8:30 - 16:30',
    'footer.saturday': 'ⴰⵙⵉⵅⵙ: 8:30 - 12:30',
    'footer.sunday': 'ⴰⵙⴰⵎⴰⵙ: ⵉⵜⵜⵓⴳⴳⴰⵍ',

    // BNRM Administration
    'bnrm.backoffice.title': 'ⴰⵎⴰⴳⴰⵏ ⴰⴽⵛⵓⴷ ⵏ ⵜⵙⴷⴰⵡⵉⵜ ⵜⴰⵏⴰⵎⵓⵔⵜ',
    'bnrm.backoffice.subtitle': 'ⴰⵙⴼⵔⵓⴽ ⴰⵏⴰⵎⵎⴰⵙ ⵏ ⵜⵏⴰⵏⵜⵉⵏ ⵏ ⵜⵙⴷⴰⵡⵉⵜ ⵜⴰⵏⴰⵎⵓⵔⵜ',
    'bnrm.dashboard.tab': 'ⴰⴼⵍⵍⵉⵙ ⵏ ⵓⵙⴼⵔⵓⴽ',
    'bnrm.services.tab': 'ⵜⴰⵏⴰⵏⵜⵉⵏ',
    'bnrm.requests.tab': 'ⵜⵓⵜⵔⴰ',
    'bnrm.workflow.tab': 'ⴰⵙⵢⴰⴼⵓ ⵏ ⵜⵡⵓⵔⵉ',
    'bnrm.tariffs.tab': 'ⵉⵎⵍⴰⵙⵏ',
    'bnrm.parameters.tab': 'ⵜⵉⵙⵎⴽⵜⴰ',
    'bnrm.history.tab': 'ⴰⵎⵣⵔⵓⵢ',
    'bnrm.reports.tab': 'ⵉⵏⵇⵇⵉⵙⵏ',
    'bnrm.publicPortal.btn': 'ⴰⴱⵡⴰⴱ ⴰⴳⴷⵓⴷⴰⵏ',
    'bnrm.back.btn': 'ⵜⴰⵖⵓⵍⵉ',
    'bnrm.reports.btn': 'ⵉⵏⵇⵇⵉⵙⵏ',

    // BNRM Services
    'bnrm.services.title': 'ⵜⴰⵏⴰⵏⵜⵉⵏ ⵏ ⵜⵙⴷⴰⵡⵉⵜ ⵜⴰⵏⴰⵎⵓⵔⵜ',
    'bnrm.services.description': 'ⴰⵙⴼⵔⵓⴽ ⵏ ⵜⵏⴰⵏⵜⵉⵏ ⵏ ⵜⵙⴷⴰⵡⵉⵜ ⵜⴰⵏⴰⵎⵓⵔⵜ ⴰⵔ ⴰⵏⴰⵎⵓⵙ 67-99',
    'bnrm.services.add': 'ⵔⵏⵓ ⵜⴰⵏⴰⵏⵜ',
    'bnrm.services.code': 'ⴰⵙⴰⴼⴰⵔ ⵏ ⵜⵏⴰⵏⵜ',
    'bnrm.services.name': 'ⵉⵙⵎ ⵏ ⵜⵏⴰⵏⵜ',
    'bnrm.services.description.field': 'ⴰⴳⵍⴰⵎ',
    'bnrm.services.category': 'ⴰⴳⵔⴰⵡ',
    'bnrm.services.legal.reference': 'ⴰⵎⵓⵍⵓ ⴰⵏⴰⵎⵓⵙ',
    'bnrm.services.actions': 'ⵜⵉⴳⴰⵡⵉⵏ',
    'bnrm.services.edit': 'ⴰⵙⵏⴼⵍ',
    'bnrm.services.delete': 'ⴰⵙⵉⵜⵢ',

    // BNRM Tariffs
    'bnrm.tariffs.title': 'ⵉⵎⵍⴰⵙⵏ ⵉⵜⵜⵓⵙⵏⴼⵍⵏ',
    'bnrm.tariffs.description': 'ⴰⵙⴼⵔⵓⴽ ⵏ ⵉⵎⵍⴰⵙⵏ ⴰⴽⴷ ⵓⵃⵟⵟⵓ ⴰⵡⵔⵎⴰⵏ',
    'bnrm.tariffs.code': 'ⴰⵙⴰⴼⴰⵔ ⵏ ⵓⵎⵍⴰⵙ',
    'bnrm.tariffs.service': 'ⵜⴰⵏⴰⵏⵜ',
    'bnrm.tariffs.amount': 'ⴰⵛⵃⴰⵍ',
    'bnrm.tariffs.currency': 'ⴰⵎⴷⵔⵉⵎ',
    'bnrm.tariffs.condition': 'ⴰⵙⵜⵓⴷ',
    'bnrm.tariffs.validity': 'ⴰⴽⵓⴷ ⵏ ⵓⵙⵜⵓⴷ',
    'bnrm.tariffs.status': 'ⴰⴷⴷⴰⴷ',
    'bnrm.tariffs.active': 'ⵉⵜⵜⵓⵙⵡⵓⵔⵉ',
    'bnrm.tariffs.inactive': 'ⵓⵔ ⵉⵙⵡⵓⵔⵉ',

    // BNRM Parameters
    'bnrm.parameters.title': 'ⵜⵉⵙⵎⴽⵜⴰ ⵏ ⵓⵏⴰⴳⵔⴰⵡ',
    'bnrm.parameters.description': 'ⴰⵙⵙⵖⵜⵉ ⵏ ⵜⵙⵎⴽⵜⴰ ⵏ ⵜⵡⵓⵔⵉ',
    'bnrm.parameters.key': 'ⴰⵙⴰⵔⵓ',
    'bnrm.parameters.value': 'ⴰⵣⴰⵍ',
    'bnrm.parameters.description.field': 'ⴰⴳⵍⴰⵎ',
    'bnrm.parameters.lastUpdate': 'ⴰⵙⵏⴼⵍ ⴰⵎⴳⴳⴰⵔⵓ',

    // BNRM Workflow
    'bnrm.workflow.title': 'ⴰⵙⴼⵔⵓⴽ ⵏ ⵓⵙⵢⴰⴼⵓ ⵏ ⵜⵡⵓⵔⵉ',
    'bnrm.workflow.description': 'ⴰⵙⵙⵖⵜⵉ ⴷ ⵓⴹⴼⴰⵕ ⵏ ⵜⵖⴰⵡⵙⵉⵡⵉⵏ ⵏ ⵜⵡⵓⵔⵉ',
    'bnrm.workflow.name': 'ⵉⵙⵎ ⵏ ⵓⵙⵢⴰⴼⵓ ⵏ ⵜⵡⵓⵔⵉ',
    'bnrm.workflow.steps': 'ⵜⵉⵙⴽⴽⵉⵍⵉⵏ',
    'bnrm.workflow.create': 'ⵙⵏⵓⵍⴼⵓ ⴰⵙⵢⴰⴼⵓ ⵏ ⵜⵡⵓⵔⵉ',
    'bnrm.workflow.edit': 'ⴰⵙⵏⴼⵍ ⵏ ⵓⵙⵢⴰⴼⵓ ⵏ ⵜⵡⵓⵔⵉ',
    'bnrm.workflow.delete': 'ⴰⵙⵉⵜⵢ',
    'bnrm.workflow.activate': 'ⴰⵔⵎⴷ',
    'bnrm.workflow.deactivate': 'ⴰⴽⴽⵙ ⴰⵔⵎⴷ',
    'bnrm.workflow.confirmDelete': 'ⵜⵃⵇⵇⴰⴷ ⴰⴷ ⵜⵙⵉⵜⵢⴷ ⴰⵙⵢⴰⴼⵓ ⵏ ⵜⵡⵓⵔⵉ ⴰⴷ?',
    'bnrm.workflow.confirmActivate': 'ⵜⵃⵇⵇⴰⴷ ⴰⴷ ⵜⴰⵔⵎⴷⴷ ⴰⵙⵢⴰⴼⵓ ⵏ ⵜⵡⵓⵔⵉ ⴰⴷ?',
    'bnrm.workflow.confirmDeactivate': 'ⵜⵃⵇⵇⴰⴷ ⴰⴷ ⵜⴰⴽⴽⵙⴷ ⴰⵔⵎⴷ ⵏ ⵓⵙⵢⴰⴼⵓ ⵏ ⵜⵡⵓⵔⵉ ⴰⴷ?',

    // Legal Deposit
    'legal.deposit.title': 'ⴰⵙⴼⵔⵓⴽ ⵏ ⵓⵙⵔⵙ ⴰⵏⴰⵎⵓⵙ',
    'legal.deposit.subtitle': 'ⴰⵙⴼⵔⵓⴽ ⵏ ⵓⵙⵔⵙ ⴰⵏⴰⵎⵓⵙ ⴰⵔ ⵓⵙⵍⴳⵏ ⴰⵎⵖⵔⵉⴱⵉ',
    'legal.deposit.declarations': 'ⵉⵙⵙⵏⵎⴰⵍⵏ',
    'legal.deposit.archiving': 'ⴰⵃⵟⵟⵓ',
    'legal.deposit.reports': 'ⵉⵏⵇⵇⵉⵙⵏ',

    // Admin Settings
    'admin.settings.title': 'ⵜⵉⵙⵖⵜⵉⵏ ⵏ ⵓⵙⴼⵔⵓⴽ',
    'admin.settings.subtitle': 'ⴰⵙⵙⵖⵜⵉ ⴷ ⵓⵙⴼⵔⵓⴽ ⵏ ⵓⵏⴰⴳⵔⴰⵡ',
    'admin.permissions.title': 'ⴰⵙⴼⵔⵓⴽ ⵏ ⵉⵣⵔⴼⴰⵏ ⴷ ⵜⵙⴰⵔⵉⵏ',
    'admin.permissions.description': 'ⴰⵙⴼⵔⵓⴽ ⵏ ⵡⴰⴷⴷⴰⴼ ⵖⵔ ⵜⵢⴰⴼⵓⵜⵉⵏ',
    'admin.content.title': 'ⴰⵙⴼⵔⵓⴽ ⵏ ⵓⴳⴷⵉⵣ',
    'admin.content.description': 'ⴰⵙⴼⵔⵓⴽ ⵏ ⵉⴳⴷⵉⵣⵏ ⴷ ⵜⵓⴼⴼⵖⵉⵏ',
    'admin.users.title': 'ⴰⵙⴼⵔⵓⴽ ⵏ ⵉⵎⵙⵙⵎⵔⵙⵏ',
    'admin.users.description': 'ⴰⵙⴼⵔⵓⴽ ⵏ ⵉⵎⵉⴹⴰⵏⵏ ⵏ ⵉⵎⵙⵙⵎⵔⵙⵏ',
    'admin.activity.title': 'ⴰⴹⴼⴰⵕ ⵏ ⵜⵎⴰⵙⵙⴰⵢⵜ',
    'admin.activity.description': 'ⴰⴹⴼⴰⵕ ⴷ ⵓⵣⵎⵎⵓ ⵏ ⵓⵏⴰⴳⵔⴰⵡ',
    'admin.archiving.title': 'ⴰⵙⴼⵔⵓⴽ ⵏ ⵓⵃⵟⵟⵓ',
    'admin.archiving.description': 'ⴰⵙⵙⵖⵜⵉ ⵏ ⵜⵙⵔⵜⵉⵜⵉⵏ ⵏ ⵓⵃⵟⵟⵓ',
    'admin.legal.deposit.title': 'ⴰⵙⵔⵙ ⴰⵏⴰⵎⵓⵙ',
    'admin.legal.deposit.description': 'ⴰⵙⴼⵔⵓⴽ ⵏ ⵓⵙⵔⵙ ⴰⵏⴰⵎⵓⵙ',
    'admin.subscriptions.title': 'ⴰⵙⴼⵔⵓⴽ ⵏ ⵉⵛⵜⴰⵔⴰⴽⵏ',
    'admin.subscriptions.description': 'ⵉⵖⴰⵡⴰⵙⵏ ⴷ ⵉⵛⵜⴰⵔⴰⴽⵏ ⵏ ⵉⵎⵙⵙⵎⵔⵙⵏ',
    'admin.bnrm.tariffs.title': 'ⴰⵙⴼⵔⵓⴽ ⵏ ⵉⵎⵍⴰⵙⵏ ⵏ ⵜⵙⴷⴰⵡⵉⵜ ⵜⴰⵏⴰⵎⵓⵔⵜ',
    'admin.bnrm.tariffs.description': 'ⴰⵙⴼⵔⵓⴽ ⵏ ⵉⵎⵍⴰⵙⵏ ⴷ ⵜⵏⴰⵏⵜⵉⵏ ⵏ ⵜⵙⴷⴰⵡⵉⵜ ⵜⴰⵏⴰⵎⵓⵔⵜ',
    'admin.bnrm.backoffice.title': 'ⴰⵎⴰⴳⴰⵏ ⴰⴽⵛⵓⴷ ⵏ ⵜⵙⴷⴰⵡⵉⵜ ⵜⴰⵏⴰⵎⵓⵔⵜ',
    'admin.bnrm.backoffice.description': 'ⴰⴳⴷⴰⵍ ⵏ ⵓⵙⴼⵔⵓⴽ ⵏ ⵜⵙⴷⴰⵡⵉⵜ ⵜⴰⵏⴰⵎⵓⵔⵜ',
    'admin.workflow.title': 'ⴰⵙⴼⵔⵓⴽ ⵏ ⵓⵙⵢⴰⴼⵓ ⵏ ⵜⵡⵓⵔⵉ',
    'admin.workflow.description': 'ⴰⵙⵙⵖⵜⵉ ⵏ ⵜⵖⴰⵡⵙⵉⵡⵉⵏ ⵏ ⵜⵡⵓⵔⵉ',

    // Common Actions
    'common.save': 'ⴰⵙⵎⴽⵜⵉ',
    'common.cancel': 'ⴰⵙⵔⵎⵙ',
    'common.edit': 'ⴰⵙⵏⴼⵍ',
    'common.delete': 'ⴰⵙⵉⵜⵢ',
    'common.add': 'ⵔⵏⵓ',
    'common.confirm': 'ⴰⵙⵏⵜⵎ',
    'common.close': 'ⴰⴷⴳⴰⵔ',
    'common.loading': 'ⴰⵛⵓⴱⴱⵉ...',
    'common.error': 'ⴰⵣⴳⵍ',
    'common.success': 'ⵢⵓⴽⵣ',
    'common.warning': 'ⴰⵖⵔⴰⵙ',
    'common.yes': 'ⵢⴰⵀ',
    'common.no': 'ⵓⵀⵓ',
    'common.search': 'ⴰⵔⵣⵣⵓ',
    'common.filter': 'ⴰⵙⴽⵛⵉⴼ',
    'common.export': 'ⴰⵙⵓⴼⵖ',
    'common.import': 'ⴰⴽⵛⵓⵎ',
    'common.view': 'ⴰⵏⵏⴰⵢ',
    'common.download': 'ⴰⵣⴷⴰⵎ'
  },
  en: {
    // Header
    'header.title': 'National Library of the Kingdom of Morocco',
    'header.home': 'Home',
    'header.catalog': 'Catalog',
    'header.collections': 'Digital Collections',
    'header.services': 'Services',
    'header.heritage': 'Heritage',
    'header.contact': 'Contact',
    'header.search': 'Search in catalog...',
    'header.searchMobile': 'Search...',
    
    // Navigation
    'nav.discover': 'Discover the Library',
    'nav.services': 'Access our services',
    'nav.explore': 'Explore heritage',
    'nav.practical.info': 'Practical information',
    'nav.history.missions': 'History and missions',
    'nav.inscription.access': 'Registration and access',
    'nav.specialized.services': 'Specialized services',
    'nav.collections': 'Collections',
    'nav.exhibitions.events': 'Exhibitions and events',
    'nav.publications': 'Publications',
    'nav.schedules.access': 'Schedules and access',
    'nav.services.catalog': 'Services catalog and rates',
    'nav.virtual.tours': 'Virtual tours',
    'nav.donors': 'Our donors',
    'nav.library.history': 'Library history',
    'nav.management.message': 'Management message',
    'nav.organization.chart': 'Organization chart',
    'nav.login': 'Login',
    'nav.dashboard': 'Dashboard',
    
    // Additional navigation and menus
    'nav.legal.deposit': 'Legal Deposit',
    'nav.reproduction.request': 'Reproduction Request',
    'nav.restoration.request': 'Restoration Request',
    'nav.online.registration': 'Online Registration / Re-registration',
    'nav.consult.national.library': 'Consult National Library',
    'nav.reserve.book': 'Reserve a Book',
    'nav.reserve.spaces': 'Reserve Our Spaces',
    'nav.specialized.collections': 'Specialized Collections',
    'nav.digitized.collections': 'Digitized Collections',
    'nav.donated.collections': 'Donated Collections',
    'nav.manuscripts': 'Manuscripts',
    'nav.monographs': 'Monographs',
    
    // Tabs and interface elements
    'tabs.services': 'Services',
    'tabs.parameters': 'Parameters',
    'tabs.tariffs': 'Configurable Tariffs',
    'tabs.history': 'History',
    'tabs.logs': 'Logs',
    'tabs.settings': 'Settings',
    
    // News and Culture menus
    'nav.consult.news': 'Consult Our News',
    'nav.collaborate': 'Collaborate with Us',
    'nav.news.section': 'News',
    'nav.culture.section': 'Culture',
    'nav.news.publications': 'News and Publications',
    'nav.news.publications.desc': 'New acquisitions, collection news',
    'nav.they.talk.about.us': 'They Talk About Us',
    'nav.they.talk.about.us.desc': 'Press review and mentions',
    'nav.cultural.programming': 'Our Cultural Programming',
    'nav.cultural.programming.desc': 'Agenda, exhibitions',
    'nav.national.collaborations': 'National Collaborations',
    'nav.national.collaborations.desc': 'Partnerships with Moroccan institutions',
    'nav.international.collaborations': 'International Collaborations',
    'nav.international.collaborations.desc': 'International exchanges and cooperation',
    
    // Hero
    'hero.title': 'Guardian of Moroccan Written Heritage',
    'hero.subtitle': 'Discover the documentary treasures of the Kingdom through our collections of ancient manuscripts, rare books and exceptional digital resources.',
    'hero.exploreBtn': 'Explore Catalog',
    'hero.digitaBtn': 'Digital Collections',
    
    // Services
    'services.title': 'Our Services',
    'services.subtitle': 'Excellence services for researchers, students and enthusiasts of Moroccan heritage',
    'services.consultation.title': 'On-site Consultation',
    'services.consultation.desc': 'Access our collections in specialized reading rooms with the support of our experts.',
    'services.digitization.title': 'Digitization',
    'services.digitization.desc': 'Heritage preservation and accessibility through our high-quality digitization programs.',
    'services.research.title': 'Research Assistance',
    'services.research.desc': 'Benefit from the expertise of our librarians for your academic and scientific research.',
    'services.legal.title': 'Legal Deposit',
    'services.legal.desc': 'Official service for collecting and preserving national editorial production.',
    'services.training.title': 'Training',
    'services.training.desc': 'Training programs in information sciences and heritage preservation.',
    'services.exhibitions.title': 'Exhibitions',
    'services.exhibitions.desc': 'Discover our temporary and permanent exhibitions showcasing our heritage.',
    
    // Collections
    'collections.title': 'Digital Collections',
    'collections.subtitle': 'Explore our digitized heritage accessible online',
    'collections.manuscripts.title': 'Ancient Manuscripts',
    'collections.manuscripts.count': '15,000+ manuscripts',
    'collections.manuscripts.desc': 'Exceptional collection of Arabic, Berber and Hebrew manuscripts from the Middle Ages to the modern era.',
    'collections.rare.title': 'Rare Books',
    'collections.rare.count': '25,000+ works',
    'collections.rare.desc': 'First editions, incunabula and precious works of Maghrebi and Oriental literature.',
    'collections.maps.title': 'Historical Maps',
    'collections.maps.count': '3,500+ maps',
    'collections.maps.desc': 'Historical cartography of Morocco and North Africa from the 15th to 20th century.',
    'collections.periodicals.title': 'Periodicals',
    'collections.periodicals.count': '12,000+ titles',
    'collections.periodicals.desc': 'Moroccan and Maghrebi press and magazines since the 19th century.',
    
    // Footer
    'footer.quickLinks': 'Quick Links',
    'footer.services': 'Services',
    'footer.collections': 'Collections',
    'footer.about': 'About',
    'footer.contact': 'Contact',
    'footer.hours': 'Hours',
    'footer.location': 'Ibn Battuta Avenue, Rabat',
    'footer.phone': 'Phone',
    'footer.email': 'Email',
    'footer.social': 'Social Media',
    'footer.rights': 'All rights reserved.',
    'footer.monday': 'Monday - Friday: 8:30 AM - 4:30 PM',
    'footer.saturday': 'Saturday: 8:30 AM - 12:30 PM',
    'footer.sunday': 'Sunday: Closed',

    // BNRM Administration
    'bnrm.backoffice.title': 'BNRM Back Office',
    'bnrm.backoffice.subtitle': 'Centralized management of National Library services',
    'bnrm.dashboard.tab': 'Dashboard',
    'bnrm.services.tab': 'Services',
    'bnrm.requests.tab': 'Requests',
    'bnrm.workflow.tab': 'Workflows',
    'bnrm.tariffs.tab': 'Tariffs',
    'bnrm.parameters.tab': 'Parameters',
    'bnrm.history.tab': 'History',
    'bnrm.reports.tab': 'Reports',
    'bnrm.publicPortal.btn': 'Public Portal',
    'bnrm.back.btn': 'Back',
    'bnrm.reports.btn': 'Reports',

    // BNRM Services
    'bnrm.services.title': 'BNRM Services',
    'bnrm.services.description': 'Management of National Library services according to Law 67-99',
    'bnrm.services.add': 'Add Service',
    'bnrm.services.code': 'Service Code',
    'bnrm.services.name': 'Service Name',
    'bnrm.services.description.field': 'Description',
    'bnrm.services.category': 'Category',
    'bnrm.services.legal.reference': 'Legal Reference',
    'bnrm.services.actions': 'Actions',
    'bnrm.services.edit': 'Edit',
    'bnrm.services.delete': 'Delete',

    // BNRM Tariffs
    'bnrm.tariffs.title': 'Configurable Tariffs',
    'bnrm.tariffs.description': 'Tariff management with automatic history tracking',
    'bnrm.tariffs.code': 'Tariff Code',
    'bnrm.tariffs.service': 'Service',
    'bnrm.tariffs.amount': 'Amount',
    'bnrm.tariffs.currency': 'Currency',
    'bnrm.tariffs.condition': 'Condition',
    'bnrm.tariffs.validity': 'Validity Period',
    'bnrm.tariffs.status': 'Status',
    'bnrm.tariffs.active': 'Active',
    'bnrm.tariffs.inactive': 'Inactive',

    // BNRM Parameters
    'bnrm.parameters.title': 'System Parameters',
    'bnrm.parameters.description': 'Configuration of operational parameters',
    'bnrm.parameters.key': 'Key',
    'bnrm.parameters.value': 'Value',
    'bnrm.parameters.description.field': 'Description',
    'bnrm.parameters.lastUpdate': 'Last Update',

    // BNRM Workflow
    'bnrm.workflow.title': 'Workflow Management',
    'bnrm.workflow.description': 'Configuration and monitoring of business processes',
    'bnrm.workflow.name': 'Workflow Name',
    'bnrm.workflow.steps': 'Steps',
    'bnrm.workflow.create': 'Create Workflow',
    'bnrm.workflow.edit': 'Edit Workflow',
    'bnrm.workflow.delete': 'Delete',
    'bnrm.workflow.activate': 'Activate',
    'bnrm.workflow.deactivate': 'Deactivate',
    'bnrm.workflow.confirmDelete': 'Are you sure you want to delete this workflow?',
    'bnrm.workflow.confirmActivate': 'Are you sure you want to activate this workflow?',
    'bnrm.workflow.confirmDeactivate': 'Are you sure you want to deactivate this workflow?',

    // Legal Deposit
    'legal.deposit.title': 'Legal Deposit Management',
    'legal.deposit.subtitle': 'Legal deposit administration according to Moroccan legislation',
    'legal.deposit.declarations': 'Declarations',
    'legal.deposit.archiving': 'Archiving',
    'legal.deposit.reports': 'Reports',

    // Admin Settings
    'admin.settings.title': 'Administration Settings',
    'admin.settings.subtitle': 'System configuration and management',
    'admin.permissions.title': 'Rights and Permissions Management',
    'admin.permissions.description': 'Control access to functionalities',
    'admin.content.title': 'Content Management',
    'admin.content.description': 'Manage content and publications',
    'admin.users.title': 'User Management',
    'admin.users.description': 'User account administration',
    'admin.activity.title': 'Activity Monitoring',
    'admin.activity.description': 'System monitoring and logs',
    'admin.archiving.title': 'Archiving Management',
    'admin.archiving.description': 'Archiving policy configuration',
    'admin.legal.deposit.title': 'Legal Deposit',
    'admin.legal.deposit.description': 'Legal deposit administration',
    'admin.subscriptions.title': 'Subscription Management',
    'admin.subscriptions.description': 'User plans and subscriptions',
    'admin.bnrm.tariffs.title': 'BNRM Tariff Management',
    'admin.bnrm.tariffs.description': 'Manage BNRM tariffs and services',
    'admin.bnrm.backoffice.title': 'BNRM Back Office',
    'admin.bnrm.backoffice.description': 'BNRM administration interface',
    'admin.workflow.title': 'Workflow Management',
    'admin.workflow.description': 'Business process configuration',

    // Common Actions
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.add': 'Add',
    'common.confirm': 'Confirm',
    'common.close': 'Close',
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.warning': 'Warning',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.export': 'Export',
    'common.import': 'Import',
    'common.view': 'View',
    'common.download': 'Download'
  },
  es: {
    // Header
    'header.title': 'Biblioteca Nacional del Reino de Marruecos',
    'header.home': 'Inicio',
    'header.catalog': 'Catálogo',
    'header.collections': 'Colecciones Digitales',
    'header.services': 'Servicios',
    'header.heritage': 'Patrimonio',
    'header.contact': 'Contacto',
    'header.search': 'Buscar en el catálogo...',
    'header.searchMobile': 'Buscar...',
    
    // Navigation
    'nav.discover': 'Descubrir la Biblioteca',
    'nav.services': 'Acceder a nuestros servicios',
    'nav.explore': 'Explorar el patrimonio',
    'nav.practical.info': 'Información práctica',
    'nav.history.missions': 'Historia y misiones',
    'nav.inscription.access': 'Inscripción y acceso',
    'nav.specialized.services': 'Servicios especializados',
    'nav.collections': 'Colecciones',
    'nav.exhibitions.events': 'Exposiciones y eventos',
    'nav.publications': 'Publicaciones',
    'nav.schedules.access': 'Horarios y acceso',
    'nav.services.catalog': 'Catálogo de servicios y tarifas',
    'nav.virtual.tours': 'Visitas virtuales',
    'nav.donors': 'Nuestros donantes',
    'nav.library.history': 'Historia de la biblioteca',
    'nav.management.message': 'Mensaje de la Dirección',
    'nav.organization.chart': 'Organigrama',
    'nav.login': 'Iniciar sesión',
    'nav.dashboard': 'Panel de control',
    
    // Additional navigation and menus
    'nav.legal.deposit': 'Depósito legal',
    'nav.reproduction.request': 'Solicitud de reproducción',
    'nav.restoration.request': 'Solicitud de restauración',
    'nav.online.registration': 'Inscripción en línea / reinscripción',
    'nav.consult.national.library': 'Consultar la Biblioteca Nacional',
    'nav.reserve.book': 'Reservar un documento',
    'nav.reserve.spaces': 'Reservar nuestros espacios',
    'nav.specialized.collections': 'Colecciones especializadas',
    'nav.digitized.collections': 'Colecciones digitalizadas',
    'nav.donated.collections': 'Colecciones donadas',
    'nav.manuscripts': 'Manuscritos',
    'nav.monographs': 'Monografías',
    
    // Tabs and interface elements
    'tabs.services': 'Servicios',
    'tabs.parameters': 'Parámetros',
    'tabs.tariffs': 'Tarifas Configurables',
    'tabs.history': 'Historial',
    'tabs.logs': 'Historial',
    'tabs.settings': 'Configuración',
    
    // News and Culture menus
    'nav.consult.news': 'Consultar nuestras noticias',
    'nav.collaborate': 'Colaborar con nosotros',
    'nav.news.section': 'Noticias',
    'nav.culture.section': 'Cultura',
    'nav.news.publications': 'Noticias y publicaciones',
    'nav.news.publications.desc': 'Nuevas adquisiciones, noticias del fondo',
    'nav.they.talk.about.us': 'Hablan de nosotros',
    'nav.they.talk.about.us.desc': 'Revista de prensa y menciones',
    'nav.cultural.programming': 'Nuestra programación cultural',
    'nav.cultural.programming.desc': 'Agenda, exposiciones',
    'nav.national.collaborations': 'Colaboraciones nacionales',
    'nav.national.collaborations.desc': 'Asociaciones con instituciones marroquíes',
    'nav.international.collaborations': 'Colaboraciones internacionales',
    'nav.international.collaborations.desc': 'Intercambios y cooperación internacional',
    
    // Hero
    'hero.title': 'Guardiana del Patrimonio Escrito Marroquí',
    'hero.subtitle': 'Descubre los tesoros documentales del Reino a través de nuestras colecciones de manuscritos antiguos, libros raros y recursos digitales excepcionales.',
    'hero.exploreBtn': 'Explorar el Catálogo',
    'hero.digitaBtn': 'Colecciones Digitales',
    
    // Services
    'services.title': 'Nuestros Servicios',
    'services.subtitle': 'Servicios de excelencia para investigadores, estudiantes y apasionados del patrimonio marroquí',
    'services.consultation.title': 'Consulta Presencial',
    'services.consultation.desc': 'Acceda a nuestras colecciones en nuestras salas de lectura especializadas con el acompañamiento de nuestros expertos.',
    'services.digitization.title': 'Digitalización',
    'services.digitization.desc': 'Preservación y accesibilidad del patrimonio a través de nuestros programas de digitalización de alta calidad.',
    'services.research.title': 'Ayuda a la Investigación',
    'services.research.desc': 'Benefíciese de la experiencia de nuestros bibliotecarios para sus investigaciones académicas y científicas.',
    'services.legal.title': 'Depósito Legal',
    'services.legal.desc': 'Servicio oficial de recopilación y conservación de la producción editorial nacional.',
    'services.training.title': 'Formación',
    'services.training.desc': 'Programas de formación en ciencias de la información y preservación del patrimonio.',
    'services.exhibitions.title': 'Exposiciones',
    'services.exhibitions.desc': 'Descubra nuestras exposiciones temporales y permanentes que valorizan nuestro patrimonio.',
    
    // Collections
    'collections.title': 'Colecciones Digitales',
    'collections.subtitle': 'Explore nuestro patrimonio digitalizado accesible en línea',
    'collections.manuscripts.title': 'Manuscritos Antiguos',
    'collections.manuscripts.count': '15,000+ manuscritos',
    'collections.manuscripts.desc': 'Colección excepcional de manuscritos árabes, amazighes y hebreos desde la Edad Media hasta la época moderna.',
    'collections.rare.title': 'Libros Raros',
    'collections.rare.count': '25,000+ obras',
    'collections.rare.desc': 'Ediciones príncipes, incunables y obras preciosas de la literatura magrebí y oriental.',
    'collections.maps.title': 'Mapas Históricos',
    'collections.maps.count': '3,500+ mapas',
    'collections.maps.desc': 'Cartografía histórica de Marruecos y África del Norte del siglo XV al XX.',
    'collections.periodicals.title': 'Periódicos',
    'collections.periodicals.count': '12,000+ títulos',
    'collections.periodicals.desc': 'Prensa y revistas marroquíes y magrebíes desde el siglo XIX.',
    
    // Footer
    'footer.quickLinks': 'Enlaces Rápidos',
    'footer.services': 'Servicios',
    'footer.collections': 'Colecciones',
    'footer.about': 'Acerca de',
    'footer.contact': 'Contacto',
    'footer.hours': 'Horarios',
    'footer.location': 'Avenida Ibn Battuta, Rabat',
    'footer.phone': 'Teléfono',
    'footer.email': 'Correo electrónico',
    'footer.social': 'Redes Sociales',
    'footer.rights': 'Todos los derechos reservados.',
    'footer.monday': 'Lunes - Viernes: 8h30 - 16h30',
    'footer.saturday': 'Sábado: 8h30 - 12h30',
    'footer.sunday': 'Domingo: Cerrado',

    // BNRM Administration
    'bnrm.backoffice.title': 'Back Office BNRM',
    'bnrm.backoffice.subtitle': 'Gestión centralizada de los servicios de la Biblioteca Nacional',
    'bnrm.dashboard.tab': 'Panel de Control',
    'bnrm.services.tab': 'Servicios',
    'bnrm.requests.tab': 'Solicitudes',
    'bnrm.workflow.tab': 'Flujos de Trabajo',
    'bnrm.tariffs.tab': 'Tarifas',
    'bnrm.parameters.tab': 'Parámetros',
    'bnrm.history.tab': 'Historial',
    'bnrm.reports.tab': 'Informes',
    'bnrm.publicPortal.btn': 'Portal Público',
    'bnrm.back.btn': 'Volver',
    'bnrm.reports.btn': 'Informes',

    // BNRM Services
    'bnrm.services.title': 'Servicios BNRM',
    'bnrm.services.description': 'Gestión de los servicios de la Biblioteca Nacional según la Ley 67-99',
    'bnrm.services.add': 'Añadir un Servicio',
    'bnrm.services.code': 'Código de Servicio',
    'bnrm.services.name': 'Nombre del Servicio',
    'bnrm.services.description.field': 'Descripción',
    'bnrm.services.category': 'Categoría',
    'bnrm.services.legal.reference': 'Referencia Legal',
    'bnrm.services.actions': 'Acciones',
    'bnrm.services.edit': 'Modificar',
    'bnrm.services.delete': 'Eliminar',

    // BNRM Tariffs
    'bnrm.tariffs.title': 'Tarifas Configurables',
    'bnrm.tariffs.description': 'Gestión de tarifas con historización automática',
    'bnrm.tariffs.code': 'Código de Tarifa',
    'bnrm.tariffs.service': 'Servicio',
    'bnrm.tariffs.amount': 'Importe',
    'bnrm.tariffs.currency': 'Moneda',
    'bnrm.tariffs.condition': 'Condición',
    'bnrm.tariffs.validity': 'Período de Validez',
    'bnrm.tariffs.status': 'Estado',
    'bnrm.tariffs.active': 'Activo',
    'bnrm.tariffs.inactive': 'Inactivo',

    // BNRM Parameters
    'bnrm.parameters.title': 'Parámetros del Sistema',
    'bnrm.parameters.description': 'Configuración de parámetros operativos',
    'bnrm.parameters.key': 'Clave',
    'bnrm.parameters.value': 'Valor',
    'bnrm.parameters.description.field': 'Descripción',
    'bnrm.parameters.lastUpdate': 'Última Actualización',

    // BNRM Workflow
    'bnrm.workflow.title': 'Gestión de Flujos de Trabajo',
    'bnrm.workflow.description': 'Configuración y seguimiento de procesos de negocio',
    'bnrm.workflow.name': 'Nombre del Flujo',
    'bnrm.workflow.steps': 'Etapas',
    'bnrm.workflow.create': 'Crear un Flujo',
    'bnrm.workflow.edit': 'Modificar el Flujo',
    'bnrm.workflow.delete': 'Eliminar',
    'bnrm.workflow.activate': 'Activar',
    'bnrm.workflow.deactivate': 'Desactivar',
    'bnrm.workflow.confirmDelete': '¿Está seguro de que desea eliminar este flujo de trabajo?',
    'bnrm.workflow.confirmActivate': '¿Está seguro de que desea activar este flujo de trabajo?',
    'bnrm.workflow.confirmDeactivate': '¿Está seguro de que desea desactivar este flujo de trabajo?',

    // Legal Deposit
    'legal.deposit.title': 'Gestión del Depósito Legal',
    'legal.deposit.subtitle': 'Administración del depósito legal según la legislación marroquí',
    'legal.deposit.declarations': 'Declaraciones',
    'legal.deposit.archiving': 'Archivado',
    'legal.deposit.reports': 'Informes',

    // Admin Settings
    'admin.settings.title': 'Configuración de Administración',
    'admin.settings.subtitle': 'Configuración y gestión del sistema',
    'admin.permissions.title': 'Gestión de Derechos y Permisos',
    'admin.permissions.description': 'Controlar el acceso a las funcionalidades',
    'admin.content.title': 'Gestión de contenido',
    'admin.content.description': 'Gestionar contenidos y publicaciones',
    'admin.users.title': 'Gestión de Usuarios',
    'admin.users.description': 'Administración de cuentas de usuario',
    'admin.activity.title': 'Monitorización de Actividad',
    'admin.activity.description': 'Monitoreo y registros del sistema',
    'admin.archiving.title': 'Gestión de Archivado',
    'admin.archiving.description': 'Configuración de políticas de archivado',
    'admin.legal.deposit.title': 'Depósito Legal',
    'admin.legal.deposit.description': 'Administración del depósito legal',
    'admin.subscriptions.title': 'Gestión de Suscripciones',
    'admin.subscriptions.description': 'Planes y suscripciones de usuarios',
    'admin.bnrm.tariffs.title': 'Gestión de Tarifas BNRM',
    'admin.bnrm.tariffs.description': 'Gestionar tarifas y servicios de la BNRM',
    'admin.bnrm.backoffice.title': 'Back Office BNRM',
    'admin.bnrm.backoffice.description': 'Interfaz de administración BNRM',
    'admin.workflow.title': 'Gestión de Flujos de Trabajo',
    'admin.workflow.description': 'Configuración de procesos de negocio',

    // Common Actions
    'common.save': 'Guardar',
    'common.cancel': 'Cancelar',
    'common.edit': 'Modificar',
    'common.delete': 'Eliminar',
    'common.add': 'Añadir',
    'common.confirm': 'Confirmar',
    'common.close': 'Cerrar',
    'common.loading': 'Cargando...',
    'common.error': 'Error',
    'common.success': 'Éxito',
    'common.warning': 'Atención',
    'common.yes': 'Sí',
    'common.no': 'No',
    'common.search': 'Buscar',
    'common.filter': 'Filtrar',
    'common.export': 'Exportar',
    'common.import': 'Importar',
    'common.view': 'Ver',
    'common.download': 'Descargar'
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const savedLanguage = localStorage.getItem('bnrm-language');
    return (savedLanguage as Language) || 'fr';
  });

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('bnrm-language', lang);
  };

  const t = (key: string): string => {
    // Check digital library translations first, then fallback to general translations
    const dlTranslations = digitalLibraryTranslations[language] as Record<string, string>;
    if (dlTranslations && dlTranslations[key]) {
      return dlTranslations[key];
    }
    // Fallback to French for languages without full translations (es, amz)
    const langTranslations = translations[language as keyof typeof translations] || translations.fr;
    return langTranslations[key] || key;
  };

  const isRTL = language === 'ar';

  useEffect(() => {
    document.documentElement.dir = isRTL ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language, isRTL]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};