-- Insertion de données d'exemple pour les propositions de programmation culturelle

-- D'abord, récupérer un user_id valide (admin ou premier utilisateur)
DO $$
DECLARE
  sample_user_id UUID;
BEGIN
  -- Récupérer le premier utilisateur ou créer un ID temporaire
  SELECT id INTO sample_user_id FROM auth.users LIMIT 1;
  
  IF sample_user_id IS NULL THEN
    sample_user_id := gen_random_uuid();
  END IF;

  -- Insérer les propositions d'exemple
  INSERT INTO public.cultural_program_proposals (
    requester_id,
    requester_name,
    requester_email,
    activity_type,
    title,
    description,
    proposed_date,
    proposed_time,
    duration_hours,
    expected_attendees,
    space_requirements,
    equipment_needs,
    budget_estimate,
    status,
    committee_comments,
    committee_signature,
    signed_by,
    signed_at
  ) VALUES
  (
    sample_user_id,
    'Auteur Y',
    'auteur.y@example.ma',
    'Conférence',
    'Mémoire du livre marocain',
    'Une conférence sur l''histoire et l''évolution du livre marocain à travers les siècles. Cette intervention abordera les différentes étapes de la production du livre au Maroc, des manuscrits traditionnels aux éditions modernes.',
    '2025-11-22',
    '14:00',
    2,
    80,
    'Salle de conférence avec capacité de 100 personnes',
    'Projecteur, micro, système audio',
    5000,
    'en_attente',
    NULL,
    NULL,
    NULL,
    NULL
  ),
  (
    sample_user_id,
    'Association Littéraire Casablanca',
    'contact@alc.ma',
    'Atelier',
    'Atelier d''écriture créative',
    'Atelier d''initiation à l''écriture créative destiné aux jeunes auteurs. L''atelier comprendra des exercices pratiques, des discussions sur les techniques narratives et des sessions de critique constructive.',
    '2025-12-05',
    '10:00',
    4,
    25,
    'Salle de travail avec tables modulables',
    'Tableaux blancs, marqueurs, supports pour projections',
    3500,
    'valide',
    'Excellente proposition qui s''inscrit dans notre programmation de soutien aux jeunes talents. Le format de l''atelier est bien adapté au public cible.',
    'Dr. Fatima El Amrani, Directrice DAC',
    sample_user_id,
    NOW() - INTERVAL '3 days'
  ),
  (
    sample_user_id,
    'Professeur Ahmed Bennis',
    'a.bennis@university.ma',
    'Table ronde',
    'Le patrimoine manuscrit marocain : enjeux de conservation',
    'Table ronde réunissant des experts en conservation, des historiens et des bibliothécaires pour discuter des défis actuels de la préservation du patrimoine manuscrit marocain et des solutions innovantes.',
    '2025-11-30',
    '15:30',
    3,
    50,
    'Auditorium',
    'Micro pour 6 intervenants, écran de projection, caméra pour enregistrement',
    8000,
    'en_attente',
    NULL,
    NULL,
    NULL,
    NULL
  ),
  (
    sample_user_id,
    'Maison d''édition Al Madariss',
    'events@almadariss.ma',
    'Exposition',
    'Exposition : 100 ans d''édition au Maroc',
    'Exposition retraçant un siècle d''édition marocaine à travers des livres rares, des affiches publicitaires vintage et des témoignages d''éditeurs pionniers.',
    '2025-12-15',
    '09:00',
    168,
    500,
    'Espace d''exposition principal (7 jours)',
    'Vitrines sécurisées, éclairage spécialisé, panneaux d''affichage',
    25000,
    'valide',
    'Projet d''envergure qui valorisera le patrimoine éditorial marocain. Excellent complément à nos collections permanentes.',
    'Dr. Fatima El Amrani, Directrice DAC',
    sample_user_id,
    NOW() - INTERVAL '5 days'
  ),
  (
    sample_user_id,
    'Collectif Poésie Moderne',
    'collectif.poesie@gmail.com',
    'Lecture publique',
    'Soirée de poésie contemporaine',
    'Lecture publique de poèmes contemporains par des poètes marocains émergents et confirmés. Une occasion de découvrir les nouvelles voix de la poésie marocaine.',
    '2025-11-18',
    '18:00',
    2,
    60,
    'Salle polyvalente avec configuration théâtre',
    'Micro, éclairage d''ambiance, chaises pour 70 personnes',
    2000,
    'rejete',
    NULL,
    NULL,
    NULL,
    NULL
  ),
  (
    sample_user_id,
    'Dr. Zineb Tazi',
    'z.tazi@research.ma',
    'Conférence',
    'Numérisation du patrimoine : expériences internationales',
    'Présentation des meilleures pratiques internationales en matière de numérisation et de valorisation numérique du patrimoine culturel, avec focus sur les projets européens et arabes.',
    '2025-12-10',
    '16:00',
    2,
    70,
    'Amphithéâtre',
    'Connexion internet haut débit, projecteur HD, micro sans fil',
    4000,
    'en_attente',
    NULL,
    NULL,
    NULL,
    NULL
  ),
  (
    sample_user_id,
    'Troupe Théâtrale Rabat',
    'contact@theatre-rabat.ma',
    'Spectacle',
    'Adaptation théâtrale : La Boîte à Merveilles',
    'Adaptation théâtrale du célèbre roman d''Ahmed Sefrioui. Spectacle tout public mêlant théâtre, musique traditionnelle et projections visuelles.',
    '2026-01-20',
    '19:30',
    2,
    120,
    'Auditorium avec scène équipée',
    'Système de sonorisation complet, éclairage scénique, loge pour 8 comédiens',
    15000,
    'en_attente',
    NULL,
    NULL,
    NULL,
    NULL
  ),
  (
    sample_user_id,
    'Centre Culturel Ibn Battuta',
    'ccib@culture.ma',
    'Projection',
    'Cycle de documentaires : Villes impériales du Maroc',
    'Projection de 4 documentaires consacrés aux villes impériales marocaines (Fès, Marrakech, Meknès, Rabat), suivies de discussions avec les réalisateurs.',
    '2025-12-08',
    '17:00',
    3,
    90,
    'Salle de projection',
    'Projecteur cinéma, système audio 5.1, écran grand format',
    6000,
    'valide',
    'Programmation culturelle de qualité qui enrichira notre offre audiovisuelle. Les documentaires présentés ont reçu plusieurs prix internationaux.',
    'Dr. Fatima El Amrani, Directrice DAC',
    sample_user_id,
    NOW() - INTERVAL '1 day'
  );

END $$;