-- Insertion de données de test pour les réservations d'ouvrages

-- Réservation soumise (Bibliothèque Numérique)
INSERT INTO reservations_ouvrages (
  id,
  document_id,
  document_title,
  document_author,
  document_year,
  support_type,
  support_status,
  is_free_access,
  request_physical,
  allow_physical_consultation,
  routed_to,
  statut,
  requested_date,
  motif,
  user_name,
  user_email,
  user_phone,
  user_type,
  comments,
  created_at
) VALUES (
  gen_random_uuid(),
  'DOC-2024-001',
  'Histoire de la littérature marocaine moderne',
  'Ahmed Benjelloun',
  '2023',
  'Imprimé',
  'non_numerise',
  false,
  false,
  true,
  'bibliotheque_numerique',
  'soumise',
  CURRENT_DATE + interval '7 days',
  'Recherche académique',
  'Marie Dubois',
  'marie.dubois@univ.ma',
  '0612345678',
  'Chercheur',
  'Besoin urgent pour ma thèse de doctorat',
  NOW() - interval '2 hours'
);

-- Réservation en cours (Support)
INSERT INTO reservations_ouvrages (
  id,
  document_id,
  document_title,
  document_author,
  document_year,
  support_type,
  support_status,
  is_free_access,
  request_physical,
  allow_physical_consultation,
  routed_to,
  statut,
  requested_date,
  motif,
  user_name,
  user_email,
  user_phone,
  user_type,
  comments,
  created_at
) VALUES (
  gen_random_uuid(),
  'DOC-2024-002',
  'La musique andalouse au Maroc',
  'Fatima Zahra El Alaoui',
  '2022',
  'Audiovisuel',
  'non_numerise',
  false,
  true,
  false,
  'responsable_support',
  'en_cours',
  CURRENT_DATE + interval '14 days',
  'Documentation culturelle',
  'Jean Martin',
  'jean.martin@culture.ma',
  '0623456789',
  'Professionnel',
  'Pour un projet de documentation culturelle',
  NOW() - interval '1 day'
);

-- Réservation validée
INSERT INTO reservations_ouvrages (
  id,
  document_id,
  document_title,
  document_author,
  document_year,
  support_type,
  support_status,
  is_free_access,
  request_physical,
  allow_physical_consultation,
  routed_to,
  statut,
  requested_date,
  motif,
  user_name,
  user_email,
  user_phone,
  user_type,
  comments,
  created_at,
  processed_at,
  date_validation
) VALUES (
  gen_random_uuid(),
  'DOC-2024-003',
  'Architecture traditionnelle de Fès',
  'Mohammed Tazi',
  '2021',
  'Imprimé',
  'numerise',
  false,
  false,
  true,
  'bibliotheque_numerique',
  'validee',
  CURRENT_DATE + interval '3 days',
  'Étude comparative',
  'Sophie Bernard',
  'sophie.bernard@archi.ma',
  '0634567890',
  'Étudiant',
  'Mémoire de master',
  NOW() - interval '3 days',
  NOW() - interval '1 day',
  NOW() - interval '1 day'
);

-- Réservation refusée
INSERT INTO reservations_ouvrages (
  id,
  document_id,
  document_title,
  document_author,
  document_year,
  support_type,
  support_status,
  is_free_access,
  request_physical,
  allow_physical_consultation,
  routed_to,
  statut,
  requested_date,
  motif,
  user_name,
  user_email,
  user_phone,
  user_type,
  comments,
  created_at,
  processed_at,
  date_refus,
  reason_refus
) VALUES (
  gen_random_uuid(),
  'DOC-2024-004',
  'Documents confidentiels - Archives royales',
  'Auteur anonyme',
  '1950',
  'Manuscrit',
  'non_numerise',
  false,
  true,
  false,
  'responsable_support',
  'refusee',
  CURRENT_DATE,
  'Recherche historique',
  'Ahmed El Fassi',
  'ahmed.elfassi@gmail.com',
  '0645678901',
  'Grand public',
  'Intérêt historique pour ma collection',
  NOW() - interval '5 days',
  NOW() - interval '2 days',
  NOW() - interval '2 days',
  'Document non communicable - Archives classées confidentielles'
);

-- Réservation archivée
INSERT INTO reservations_ouvrages (
  id,
  document_id,
  document_title,
  document_author,
  document_year,
  support_type,
  support_status,
  is_free_access,
  request_physical,
  allow_physical_consultation,
  routed_to,
  statut,
  requested_date,
  motif,
  user_name,
  user_email,
  user_phone,
  user_type,
  comments,
  created_at,
  processed_at,
  date_validation,
  date_archivage
) VALUES (
  gen_random_uuid(),
  'DOC-2023-155',
  'Poésie contemporaine maghrébine',
  'Leila Benkirane',
  '2019',
  'Électronique',
  'numerise',
  true,
  false,
  true,
  'bibliotheque_numerique',
  'archivee',
  CURRENT_DATE - interval '30 days',
  'Publication académique',
  'Hassan Idrissi',
  'hassan.idrissi@edu.ma',
  '0656789012',
  'Enseignant',
  'Pour mes cours de littérature',
  NOW() - interval '45 days',
  NOW() - interval '40 days',
  NOW() - interval '40 days',
  NOW() - interval '10 days'
);

-- Réservation soumise (libre accès mais demande physique)
INSERT INTO reservations_ouvrages (
  id,
  document_id,
  document_title,
  document_author,
  document_year,
  support_type,
  support_status,
  is_free_access,
  request_physical,
  allow_physical_consultation,
  routed_to,
  statut,
  requested_date,
  motif,
  user_name,
  user_email,
  user_phone,
  user_type,
  comments,
  created_at
) VALUES (
  gen_random_uuid(),
  'DOC-2024-005',
  'Catalogue de la Bibliothèque Nationale',
  'BNRM',
  '2024',
  'Imprimé',
  'libre_acces',
  true,
  true,
  true,
  'responsable_support',
  'soumise',
  CURRENT_DATE + interval '5 days',
  'Consultation',
  'Karim Tahiri',
  'karim.tahiri@outlook.com',
  '0667890123',
  'Grand public',
  'Souhaiterais consulter la version physique',
  NOW() - interval '4 hours'
);