-- Insertion des collections de manuscrits BNRM
INSERT INTO public.cote_collections (code, nom_arabe, nom_francais, type_collection, commentaire) VALUES
('D', 'الدخيرة', 'Collection Ad-Dakhira', 'Manuscrit', NULL),
('J', 'التهامي الجلاوي', 'Collection Tihami El-Glaoui', 'Manuscrit', NULL),
('BG', 'ب ج', 'Collection Ibrahim El-Glaoui', 'Manuscrit', NULL),
('K', 'الكتاني', 'Collection Kettani', 'Manuscrit', NULL),
('H', 'الحجوي', 'Collection Hajoui', 'Manuscrit', NULL),
('M', 'المقري', 'Collection Al-Maqqari', 'Manuscrit', NULL),
('TO', 'التوزاني', 'Collection At-Touzzani', 'Manuscrit', NULL),
('MR', 'الحاج المريني', 'Collection El-Hajj El-Merini', 'Manuscrit', NULL),
('AMR', 'عبد الحق المريني', 'Collection Abdelhaq El-Merini', 'Manuscrit', NULL),
('KH', 'نظارة الأوقاف', 'Collection Nadharat Al-Awqaf (Administration des Habous)', 'Manuscrit', NULL),
('Q', 'الأوقاف', 'Collection Awqaf (Habous)', 'Manuscrit', NULL),
('OUD', 'الأوداية', 'Collection Les Oudayas', 'Manuscrit', NULL),
('JK', 'جعفر الكتاني', 'Collection Jaafar El-Kettani', 'Manuscrit', NULL),
('II', 'أصول جائزة الحسن الثاني', 'Collection Oussoul – Prix Hassan II', 'Manuscrit', NULL),
('WA', 'محمد الوافي', 'Collection Mohamed El-Wafi', 'Manuscrit', NULL),
('T', 'بوطالب', 'Collection Boutaleb', 'Manuscrit', NULL),
('ARCHS', 'وثائق بن سودة المصورة', 'Collection Documents photographiques Ben Souda', 'Photo', NULL),
('S', 'بن سودة', 'Collection Ben Souda', 'Manuscrit', NULL),
('SQ', 'السقاط', 'Collection As-Saqqat', 'Manuscrit', NULL),
('HA', 'مولاي هاشم العلوي', 'Collection Moulay Hachem El-Alawi', 'Manuscrit', NULL),
('CH', 'الشفشاوني', 'Collection Chefchaoueni', 'Manuscrit', NULL),
('BR', 'برادة', 'Collection Barada', 'Manuscrit', NULL),
('MA', 'المهدي العلوي', 'Collection Mehdi El-Alawi', 'Manuscrit', NULL),
('GS', 'جسوس', 'Collection Jassous', 'Manuscrit', NULL),
('RN', 'الروندى', 'Collection Er-Roundi', 'Manuscrit', NULL),
('SK', 'الصقلي', 'Collection Es-Sekalli', 'Manuscrit', NULL),
('JKH', 'جعفر الكتاني الحفيد', 'Collection Jaafar El-Kettani (petit-fils)', 'Manuscrit', NULL),
('ARK', 'أركون', 'Collection Arkoun', 'Manuscrit', NULL),
('HB', 'حبيبة البورقادي', 'Collection Habiba El-Bourqadi', 'Manuscrit', NULL),
('N', 'الناصري', 'Collection An-Nasiri', 'Manuscrit', NULL),
('EBR', 'العبرية', 'Collection Manuscrits Hébreux', 'Manuscrit', NULL),
('CHB', 'الشبيهي', 'Collection Chbihi', 'Manuscrit', NULL),
('HZ', 'الحايك الزوويلي', 'Collection Hayek Ezzouili', 'Manuscrit', NULL),
('GH', 'الغرشي', 'Collection El-Gharshi', 'Manuscrit', NULL),
('MW', 'المهدي الوافي (مصورات)', 'Collection Mehdi El-Wafi (microfilms)', 'Manuscrit', NULL)
ON CONFLICT (code) DO UPDATE SET
  nom_arabe = EXCLUDED.nom_arabe,
  nom_francais = EXCLUDED.nom_francais,
  type_collection = EXCLUDED.type_collection;