-- Insertion d'exemples de Cartes et Plans dans la table cbn_documents
INSERT INTO cbn_documents (
  title, 
  author, 
  cote, 
  document_type, 
  support_type, 
  publication_year, 
  physical_description, 
  subject_headings, 
  keywords,
  access_level,
  consultation_mode
) VALUES 
(
  'Plan de la ville de Rabat',
  'Institut Cartographique Marocain',
  'CART-001',
  'Cartes et Plans',
  'Papier',
  1950,
  '1 plan : couleur ; 80 x 120 cm',
  ARRAY['Cartographie', 'Urbanisme'],
  ARRAY['Rabat', 'plan', 'ville'],
  'public',
  'sur_place'
),
(
  'Carte du Maroc - 1912',
  'Service Géographique de l''Armée',
  'CART-002',
  'Cartes et Plans',
  'Papier',
  1912,
  '1 carte : couleur ; 100 x 150 cm',
  ARRAY['Cartographie', 'Histoire'],
  ARRAY['Maroc', 'carte historique'],
  'public',
  'sur_place'
),
(
  'Plan du port de Casablanca',
  'Direction des Travaux Publics',
  'CART-003',
  'Cartes et Plans',
  'Papier',
  1935,
  '1 plan : noir et blanc ; 60 x 90 cm',
  ARRAY['Ports', 'Infrastructure'],
  ARRAY['Casablanca', 'port', 'plan'],
  'public',
  'sur_place'
),
(
  'Carte topographique du Rif',
  'Institut Géographique National',
  'CART-004',
  'Cartes et Plans',
  'Papier',
  1965,
  '1 carte : couleur ; 100 x 120 cm',
  ARRAY['Topographie', 'Géographie'],
  ARRAY['Rif', 'montagne', 'topographie'],
  'public',
  'sur_place'
),
(
  'Plan de Fès - Médina',
  'Ministère de l''Intérieur',
  'CART-005',
  'Cartes et Plans',
  'Papier',
  1980,
  '1 plan : couleur ; 70 x 100 cm',
  ARRAY['Urbanisme', 'Patrimoine'],
  ARRAY['Fès', 'médina', 'plan urbain'],
  'public',
  'sur_place'
),
(
  'Carte routière du Maroc',
  'Ministère de l''Équipement',
  'CART-006',
  'Cartes et Plans',
  'Papier',
  1995,
  '1 carte : couleur ; 90 x 120 cm',
  ARRAY['Transport', 'Infrastructure'],
  ARRAY['Maroc', 'routes', 'carte routière'],
  'public',
  'sur_place'
),
(
  'Plan de développement urbain de Marrakech',
  'Agence Urbaine de Marrakech',
  'CART-007',
  'Cartes et Plans',
  'Papier',
  2005,
  '1 plan : couleur ; 100 x 150 cm',
  ARRAY['Urbanisme', 'Aménagement'],
  ARRAY['Marrakech', 'urbanisme', 'développement'],
  'public',
  'sur_place'
);