-- Insertion d'exemples de manuscrits numérisés et non numérisés

-- Manuscrits numérisés (avec digital_copy_url ou file_url)
INSERT INTO manuscripts (
  title, 
  author, 
  description, 
  language, 
  period, 
  genre,
  material,
  dimensions,
  cote,
  source,
  historical_period,
  publication_year,
  status,
  access_level,
  is_visible,
  digital_copy_url,
  thumbnail_url
) VALUES 
(
  'مخطوط الأدب العربي القديم',
  'ابن خلدون',
  'مخطوط نادر يتناول الأدب العربي في العصور القديمة، تم ترميمه وتصويره رقمياً',
  'arabe',
  'العصور الوسطى',
  'أدب',
  'ورق',
  '30x20 cm',
  'MS-AR-2024-001',
  'BNRM',
  'القرن الرابع عشر',
  1377,
  'available',
  'public',
  true,
  'https://archive.org/download/arabic-manuscript-sample/arabic-manuscript.pdf',
  'https://images.unsplash.com/photo-1609220136736-443140cffec6?w=400'
),
(
  'Traité de médecine andalouse',
  'Ibn Zuhr',
  'Traité médical andalou numérisé, comprenant des prescriptions et traitements médicaux de l''époque',
  'arabe',
  'Al-Andalus',
  'sciences',
  'parchemin',
  '35x25 cm',
  'MS-AR-2024-002',
  'BNRM',
  'XIIe siècle',
  1161,
  'available',
  'public',
  true,
  'https://archive.org/download/andalusian-medicine/medicine-treatise.pdf',
  'https://images.unsplash.com/photo-1584036561566-baf8f5f1b144?w=400'
),
(
  'ⴰⵎⴰⵡⴰⵍ ⵏ ⵜⵎⴰⵣⵉⵖⵜ',
  'ⵎⵓⵃⴰⵏⴷ ⵛⴰⵡⵉ',
  'Recueil de poésies amazighes numérisées, témoignage de la richesse culturelle berbère',
  'berbère',
  'Moderne',
  'poésie',
  'papier',
  '25x18 cm',
  'MS-BER-2024-001',
  'BNRM',
  'XXe siècle',
  1952,
  'available',
  'public',
  true,
  'https://archive.org/download/berber-poetry/berber-poems.pdf',
  'https://images.unsplash.com/photo-1513185158878-8d8c2a2a3da3?w=400'
),
(
  'Histoire du Maroc médiéval',
  'Léon l''Africain',
  'Manuscrit historique numérisé décrivant le Maroc médiéval et ses dynasties',
  'français',
  'Renaissance',
  'histoire',
  'papier',
  '32x22 cm',
  'MS-FR-2024-001',
  'BNRM',
  'XVIe siècle',
  1550,
  'available',
  'restricted',
  true,
  'https://archive.org/download/morocco-history/medieval-morocco.pdf',
  'https://images.unsplash.com/photo-1476357471311-43c0db9fb2b4?w=400'
);

-- Manuscrits NON numérisés (catalogués uniquement, sans digital_copy_url)
INSERT INTO manuscripts (
  title, 
  author, 
  description, 
  language, 
  period, 
  genre,
  material,
  dimensions,
  cote,
  source,
  historical_period,
  publication_year,
  status,
  access_level,
  is_visible,
  condition_notes,
  thumbnail_url
) VALUES 
(
  'ديوان الشعر الأندلسي',
  'ابن زيدون',
  'ديوان شعري نادر من العصر الأندلسي، في انتظار الرقمنة. يحتوي على قصائد غزلية ومدائح نبوية',
  'arabe',
  'Al-Andalus',
  'poésie',
  'ورق مذهب',
  '28x19 cm',
  'MS-AR-2024-003',
  'BNRM',
  'القرن الحادي عشر',
  1013,
  'digitization',
  'restricted',
  true,
  'État de conservation moyen, nécessite une restauration avant numérisation',
  'https://images.unsplash.com/photo-1516979187457-637abb4f9353?w=400'
),
(
  'Recueil de fatawa malikites',
  'الإمام المازري',
  'Recueil juridique important non encore numérisé, contenant des avis juridiques selon l''école malikite',
  'arabe',
  'Époque médiévale',
  'droit islamique',
  'parchemin',
  '33x24 cm',
  'MS-AR-2024-004',
  'BNRM',
  'XIIe siècle',
  1141,
  'digitization',
  'restricted',
  true,
  'Manuscrit en bon état, priorité haute pour numérisation',
  'https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?w=400'
),
(
  'Correspondances diplomatiques',
  'Sultan Moulay Ismail',
  'Collection de lettres diplomatiques non numérisées entre le Maroc et les puissances européennes',
  'arabe',
  'Époque moderne',
  'histoire diplomatique',
  'papier',
  '30x21 cm',
  'MS-AR-2024-005',
  'BNRM',
  'XVIIe siècle',
  1672,
  'digitization',
  'confidential',
  true,
  'Documents sensibles, nécessite autorisation spéciale pour consultation',
  'https://images.unsplash.com/photo-1455390582262-044cdead277a?w=400'
),
(
  'ⴰⵎⴰⵡⴰⵍ ⵏ ⵜⵓⵙⵙⵏⴰ',
  'ⵄⵍⵉ ⵓⵙⴰⵢⴷ',
  'Manuscrit amazigh non numérisé traitant des connaissances traditionnelles et de la sagesse berbère',
  'berbère',
  'Traditionnel',
  'sagesse',
  'papier artisanal',
  '27x19 cm',
  'MS-BER-2024-002',
  'BNRM',
  'XIXe siècle',
  1887,
  'digitization',
  'restricted',
  true,
  'Papier fragile, nécessite précautions particulières pour numérisation',
  'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=400'
),
(
  'Traité d''astronomie marocaine',
  'محمد بن إبراهيم السوسي',
  'Traité astronomique précieux non numérisé avec calculs et observations célestes',
  'arabe',
  'Époque moderne',
  'sciences',
  'papier',
  '31x23 cm',
  'MS-AR-2024-006',
  'BNRM',
  'XVIIIe siècle',
  1745,
  'digitization',
  'public',
  true,
  'Manuscrit complet avec illustrations, planifié pour numérisation en 2025',
  'https://images.unsplash.com/photo-1462331940025-496dfbfc7564?w=400'
),
(
  'Récits de voyageurs au Maghreb',
  'Charles de Foucauld',
  'Journal de voyage manuscrit non numérisé décrivant le Maroc à la fin du XIXe siècle',
  'français',
  'Époque coloniale',
  'récits de voyage',
  'cahier',
  '24x16 cm',
  'MS-FR-2024-002',
  'BNRM',
  'XIXe siècle',
  1883,
  'digitization',
  'public',
  true,
  'Bon état général, demandes de numérisation fréquentes de chercheurs',
  'https://images.unsplash.com/photo-1506880018603-83d5b814b5a6?w=400'
);