-- Supprimer la table nationalities créée précédemment
DROP TABLE IF EXISTS public.nationalities CASCADE;

-- Créer une liste d'autocomplétion pour les nationalités
INSERT INTO public.autocomplete_lists (list_code, list_name, description, is_active, max_levels)
VALUES ('nationalities', 'Nationalités', 'Liste des nationalités pour les formulaires de dépôt légal', true, 1)
ON CONFLICT (list_code) DO NOTHING;

-- Obtenir l'id de la liste créée
DO $$ 
DECLARE
  nationality_list_id UUID;
BEGIN
  SELECT id INTO nationality_list_id FROM public.autocomplete_lists WHERE list_code = 'nationalities';
  
  -- Insérer les valeurs des nationalités
  INSERT INTO public.autocomplete_list_values (list_id, value_code, value_label, value_label_ar, level, sort_order, is_active) VALUES
  (nationality_list_id, 'AF', 'Afghane', 'أفغاني', 1, 10, true),
  (nationality_list_id, 'ZA', 'Sud-Africaine', 'جنوب أفريقي', 1, 20, true),
  (nationality_list_id, 'AL', 'Albanaise', 'ألباني', 1, 30, true),
  (nationality_list_id, 'DZ', 'Algérienne', 'جزائري', 1, 40, true),
  (nationality_list_id, 'DE', 'Allemande', 'ألماني', 1, 50, true),
  (nationality_list_id, 'US', 'Américaine', 'أمريكي', 1, 60, true),
  (nationality_list_id, 'AD', 'Andorrane', 'أندوري', 1, 70, true),
  (nationality_list_id, 'AO', 'Angolaise', 'أنغولي', 1, 80, true),
  (nationality_list_id, 'SA', 'Saoudienne', 'سعودي', 1, 90, true),
  (nationality_list_id, 'AR', 'Argentine', 'أرجنتيني', 1, 100, true),
  (nationality_list_id, 'AM', 'Arménienne', 'أرمني', 1, 110, true),
  (nationality_list_id, 'AU', 'Australienne', 'أسترالي', 1, 120, true),
  (nationality_list_id, 'AT', 'Autrichienne', 'نمساوي', 1, 130, true),
  (nationality_list_id, 'AZ', 'Azerbaïdjanaise', 'أذربيجاني', 1, 140, true),
  (nationality_list_id, 'BS', 'Bahamienne', 'باهامي', 1, 150, true),
  (nationality_list_id, 'BH', 'Bahreïnienne', 'بحريني', 1, 160, true),
  (nationality_list_id, 'BD', 'Bangladaise', 'بنغلاديشي', 1, 170, true),
  (nationality_list_id, 'BB', 'Barbadienne', 'بربادوسي', 1, 180, true),
  (nationality_list_id, 'BE', 'Belge', 'بلجيكي', 1, 190, true),
  (nationality_list_id, 'BZ', 'Bélizienne', 'بليزي', 1, 200, true),
  (nationality_list_id, 'BJ', 'Béninoise', 'بنيني', 1, 210, true),
  (nationality_list_id, 'BT', 'Bhoutanaise', 'بوتاني', 1, 220, true),
  (nationality_list_id, 'BY', 'Biélorusse', 'بيلاروسي', 1, 230, true),
  (nationality_list_id, 'BO', 'Bolivienne', 'بوليفي', 1, 240, true),
  (nationality_list_id, 'BA', 'Bosnienne', 'بوسني', 1, 250, true),
  (nationality_list_id, 'BW', 'Botswanaise', 'بوتسواني', 1, 260, true),
  (nationality_list_id, 'BR', 'Brésilienne', 'برازيلي', 1, 270, true),
  (nationality_list_id, 'BN', 'Brunéienne', 'بروناوي', 1, 280, true),
  (nationality_list_id, 'BG', 'Bulgare', 'بلغاري', 1, 290, true),
  (nationality_list_id, 'BF', 'Burkinabè', 'بوركيني', 1, 300, true),
  (nationality_list_id, 'BI', 'Burundaise', 'بوروندي', 1, 310, true),
  (nationality_list_id, 'KH', 'Cambodgienne', 'كمبودي', 1, 320, true),
  (nationality_list_id, 'CM', 'Camerounaise', 'كاميروني', 1, 330, true),
  (nationality_list_id, 'CA', 'Canadienne', 'كندي', 1, 340, true),
  (nationality_list_id, 'CV', 'Cap-verdienne', 'رأس أخضري', 1, 350, true),
  (nationality_list_id, 'CL', 'Chilienne', 'تشيلي', 1, 360, true),
  (nationality_list_id, 'CN', 'Chinoise', 'صيني', 1, 370, true),
  (nationality_list_id, 'CY', 'Chypriote', 'قبرصي', 1, 380, true),
  (nationality_list_id, 'CO', 'Colombienne', 'كولومبي', 1, 390, true),
  (nationality_list_id, 'KM', 'Comorienne', 'قمري', 1, 400, true),
  (nationality_list_id, 'CG', 'Congolaise', 'كونغولي', 1, 410, true),
  (nationality_list_id, 'CD', 'Congolaise (RDC)', 'كونغولي (الكونغو الديمقراطية)', 1, 420, true),
  (nationality_list_id, 'KR', 'Coréenne', 'كوري', 1, 430, true),
  (nationality_list_id, 'KP', 'Nord-Coréenne', 'كوري شمالي', 1, 440, true),
  (nationality_list_id, 'CR', 'Costaricienne', 'كوستاريكي', 1, 450, true),
  (nationality_list_id, 'CI', 'Ivoirienne', 'إيفواري', 1, 460, true),
  (nationality_list_id, 'HR', 'Croate', 'كرواتي', 1, 470, true),
  (nationality_list_id, 'CU', 'Cubaine', 'كوبي', 1, 480, true),
  (nationality_list_id, 'DK', 'Danoise', 'دانماركي', 1, 490, true),
  (nationality_list_id, 'DJ', 'Djiboutienne', 'جيبوتي', 1, 500, true),
  (nationality_list_id, 'DM', 'Dominiquaise', 'دومينيكي', 1, 510, true),
  (nationality_list_id, 'EG', 'Égyptienne', 'مصري', 1, 520, true),
  (nationality_list_id, 'AE', 'Émiratie', 'إماراتي', 1, 530, true),
  (nationality_list_id, 'EC', 'Équatorienne', 'إكوادوري', 1, 540, true),
  (nationality_list_id, 'ER', 'Érythréenne', 'إريتري', 1, 550, true),
  (nationality_list_id, 'ES', 'Espagnole', 'إسباني', 1, 560, true),
  (nationality_list_id, 'EE', 'Estonienne', 'إستوني', 1, 570, true),
  (nationality_list_id, 'ET', 'Éthiopienne', 'إثيوبي', 1, 580, true),
  (nationality_list_id, 'FJ', 'Fidjienne', 'فيجي', 1, 590, true),
  (nationality_list_id, 'FI', 'Finlandaise', 'فنلندي', 1, 600, true),
  (nationality_list_id, 'FR', 'Française', 'فرنسي', 1, 610, true),
  (nationality_list_id, 'GA', 'Gabonaise', 'غابوني', 1, 620, true),
  (nationality_list_id, 'GM', 'Gambienne', 'غامبي', 1, 630, true),
  (nationality_list_id, 'GE', 'Géorgienne', 'جورجي', 1, 640, true),
  (nationality_list_id, 'GH', 'Ghanéenne', 'غاني', 1, 650, true),
  (nationality_list_id, 'GR', 'Grecque', 'يوناني', 1, 660, true),
  (nationality_list_id, 'GD', 'Grenadienne', 'غرينادي', 1, 670, true),
  (nationality_list_id, 'GT', 'Guatémaltèque', 'غواتيمالي', 1, 680, true),
  (nationality_list_id, 'GN', 'Guinéenne', 'غيني', 1, 690, true),
  (nationality_list_id, 'GQ', 'Équato-guinéenne', 'غيني استوائي', 1, 700, true),
  (nationality_list_id, 'GW', 'Bissau-guinéenne', 'غيني بيساوي', 1, 710, true),
  (nationality_list_id, 'GY', 'Guyanienne', 'غوياني', 1, 720, true),
  (nationality_list_id, 'HT', 'Haïtienne', 'هايتي', 1, 730, true),
  (nationality_list_id, 'HN', 'Hondurienne', 'هندوراسي', 1, 740, true),
  (nationality_list_id, 'HU', 'Hongroise', 'مجري', 1, 750, true),
  (nationality_list_id, 'IN', 'Indienne', 'هندي', 1, 760, true),
  (nationality_list_id, 'ID', 'Indonésienne', 'إندونيسي', 1, 770, true),
  (nationality_list_id, 'IQ', 'Irakienne', 'عراقي', 1, 780, true),
  (nationality_list_id, 'IR', 'Iranienne', 'إيراني', 1, 790, true),
  (nationality_list_id, 'IE', 'Irlandaise', 'إيرلندي', 1, 800, true),
  (nationality_list_id, 'IS', 'Islandaise', 'آيسلندي', 1, 810, true),
  (nationality_list_id, 'IL', 'Israélienne', 'إسرائيلي', 1, 820, true),
  (nationality_list_id, 'IT', 'Italienne', 'إيطالي', 1, 830, true),
  (nationality_list_id, 'JM', 'Jamaïcaine', 'جامايكي', 1, 840, true),
  (nationality_list_id, 'JP', 'Japonaise', 'ياباني', 1, 850, true),
  (nationality_list_id, 'JO', 'Jordanienne', 'أردني', 1, 860, true),
  (nationality_list_id, 'KZ', 'Kazakhe', 'كازاخي', 1, 870, true),
  (nationality_list_id, 'KE', 'Kényane', 'كيني', 1, 880, true),
  (nationality_list_id, 'KG', 'Kirghize', 'قرغيزي', 1, 890, true),
  (nationality_list_id, 'KI', 'Kiribatienne', 'كيريباتي', 1, 900, true),
  (nationality_list_id, 'KW', 'Koweïtienne', 'كويتي', 1, 910, true),
  (nationality_list_id, 'LA', 'Laotienne', 'لاوسي', 1, 920, true),
  (nationality_list_id, 'LS', 'Lesothane', 'ليسوتي', 1, 930, true),
  (nationality_list_id, 'LV', 'Lettone', 'لاتفي', 1, 940, true),
  (nationality_list_id, 'LB', 'Libanaise', 'لبناني', 1, 950, true),
  (nationality_list_id, 'LR', 'Libérienne', 'ليبيري', 1, 960, true),
  (nationality_list_id, 'LY', 'Libyenne', 'ليبي', 1, 970, true),
  (nationality_list_id, 'LI', 'Liechtensteinoise', 'ليختنشتايني', 1, 980, true),
  (nationality_list_id, 'LT', 'Lituanienne', 'ليتواني', 1, 990, true),
  (nationality_list_id, 'LU', 'Luxembourgeoise', 'لوكسمبورغي', 1, 1000, true),
  (nationality_list_id, 'MK', 'Macédonienne', 'مقدوني', 1, 1010, true),
  (nationality_list_id, 'MG', 'Malgache', 'مدغشقري', 1, 1020, true),
  (nationality_list_id, 'MY', 'Malaisienne', 'ماليزي', 1, 1030, true),
  (nationality_list_id, 'MW', 'Malawienne', 'ملاوي', 1, 1040, true),
  (nationality_list_id, 'MV', 'Maldivienne', 'مالديفي', 1, 1050, true),
  (nationality_list_id, 'ML', 'Malienne', 'مالي', 1, 1060, true),
  (nationality_list_id, 'MT', 'Maltaise', 'مالطي', 1, 1070, true),
  (nationality_list_id, 'MA', 'Marocaine', 'مغربي', 1, 1080, true),
  (nationality_list_id, 'MH', 'Marshallaise', 'مارشالي', 1, 1090, true),
  (nationality_list_id, 'MU', 'Mauricienne', 'موريشي', 1, 1100, true),
  (nationality_list_id, 'MR', 'Mauritanienne', 'موريتاني', 1, 1110, true),
  (nationality_list_id, 'MX', 'Mexicaine', 'مكسيكي', 1, 1120, true),
  (nationality_list_id, 'FM', 'Micronésienne', 'ميكرونيزي', 1, 1130, true),
  (nationality_list_id, 'MD', 'Moldave', 'مولدوفي', 1, 1140, true),
  (nationality_list_id, 'MC', 'Monégasque', 'موناكي', 1, 1150, true),
  (nationality_list_id, 'MN', 'Mongole', 'منغولي', 1, 1160, true),
  (nationality_list_id, 'ME', 'Monténégrine', 'جبل أسود', 1, 1170, true),
  (nationality_list_id, 'MZ', 'Mozambicaine', 'موزمبيقي', 1, 1180, true),
  (nationality_list_id, 'MM', 'Birmane', 'بورمي', 1, 1190, true),
  (nationality_list_id, 'NA', 'Namibienne', 'ناميبي', 1, 1200, true),
  (nationality_list_id, 'NR', 'Nauruane', 'ناوروي', 1, 1210, true),
  (nationality_list_id, 'NP', 'Népalaise', 'نيبالي', 1, 1220, true),
  (nationality_list_id, 'NI', 'Nicaraguayenne', 'نيكاراغوي', 1, 1230, true),
  (nationality_list_id, 'NE', 'Nigérienne', 'نيجيري', 1, 1240, true),
  (nationality_list_id, 'NG', 'Nigériane', 'نيجيري', 1, 1250, true),
  (nationality_list_id, 'NO', 'Norvégienne', 'نرويجي', 1, 1260, true),
  (nationality_list_id, 'NZ', 'Néo-zélandaise', 'نيوزيلندي', 1, 1270, true),
  (nationality_list_id, 'OM', 'Omanaise', 'عماني', 1, 1280, true),
  (nationality_list_id, 'UG', 'Ougandaise', 'أوغندي', 1, 1290, true),
  (nationality_list_id, 'UZ', 'Ouzbèke', 'أوزبكي', 1, 1300, true),
  (nationality_list_id, 'PK', 'Pakistanaise', 'باكستاني', 1, 1310, true),
  (nationality_list_id, 'PW', 'Palaosienne', 'بالاوي', 1, 1320, true),
  (nationality_list_id, 'PA', 'Panaméenne', 'بنمي', 1, 1330, true),
  (nationality_list_id, 'PG', 'Papouane-néo-guinéenne', 'بابوا غينيا جديدة', 1, 1340, true),
  (nationality_list_id, 'PY', 'Paraguayenne', 'باراغواي', 1, 1350, true),
  (nationality_list_id, 'NL', 'Néerlandaise', 'هولندي', 1, 1360, true),
  (nationality_list_id, 'PE', 'Péruvienne', 'بيروفي', 1, 1370, true),
  (nationality_list_id, 'PH', 'Philippine', 'فلبيني', 1, 1380, true),
  (nationality_list_id, 'PL', 'Polonaise', 'بولندي', 1, 1390, true),
  (nationality_list_id, 'PT', 'Portugaise', 'برتغالي', 1, 1400, true),
  (nationality_list_id, 'QA', 'Qatarienne', 'قطري', 1, 1410, true),
  (nationality_list_id, 'RO', 'Roumaine', 'روماني', 1, 1420, true),
  (nationality_list_id, 'GB', 'Britannique', 'بريطاني', 1, 1430, true),
  (nationality_list_id, 'RU', 'Russe', 'روسي', 1, 1440, true),
  (nationality_list_id, 'RW', 'Rwandaise', 'رواندي', 1, 1450, true),
  (nationality_list_id, 'SN', 'Sénégalaise', 'سنغالي', 1, 1460, true),
  (nationality_list_id, 'RS', 'Serbe', 'صربي', 1, 1470, true),
  (nationality_list_id, 'SG', 'Singapourienne', 'سنغافوري', 1, 1480, true),
  (nationality_list_id, 'SK', 'Slovaque', 'سلوفاكي', 1, 1490, true),
  (nationality_list_id, 'SI', 'Slovène', 'سلوفيني', 1, 1500, true),
  (nationality_list_id, 'SO', 'Somalienne', 'صومالي', 1, 1510, true),
  (nationality_list_id, 'SD', 'Soudanaise', 'سوداني', 1, 1520, true),
  (nationality_list_id, 'SS', 'Sud-soudanaise', 'جنوب سوداني', 1, 1530, true),
  (nationality_list_id, 'LK', 'Sri-lankaise', 'سريلانكي', 1, 1540, true),
  (nationality_list_id, 'SE', 'Suédoise', 'سويدي', 1, 1550, true),
  (nationality_list_id, 'CH', 'Suisse', 'سويسري', 1, 1560, true),
  (nationality_list_id, 'SR', 'Surinamaise', 'سورينامي', 1, 1570, true),
  (nationality_list_id, 'SY', 'Syrienne', 'سوري', 1, 1580, true),
  (nationality_list_id, 'TJ', 'Tadjike', 'طاجيكي', 1, 1590, true),
  (nationality_list_id, 'TZ', 'Tanzanienne', 'تنزاني', 1, 1600, true),
  (nationality_list_id, 'TD', 'Tchadienne', 'تشادي', 1, 1610, true),
  (nationality_list_id, 'CZ', 'Tchèque', 'تشيكي', 1, 1620, true),
  (nationality_list_id, 'TH', 'Thaïlandaise', 'تايلندي', 1, 1630, true),
  (nationality_list_id, 'TL', 'Est-timoraise', 'تيموري شرقي', 1, 1640, true),
  (nationality_list_id, 'TG', 'Togolaise', 'توغولي', 1, 1650, true),
  (nationality_list_id, 'TN', 'Tunisienne', 'تونسي', 1, 1660, true),
  (nationality_list_id, 'TM', 'Turkmène', 'تركماني', 1, 1670, true),
  (nationality_list_id, 'TR', 'Turque', 'تركي', 1, 1680, true),
  (nationality_list_id, 'UA', 'Ukrainienne', 'أوكراني', 1, 1690, true),
  (nationality_list_id, 'UY', 'Uruguayenne', 'أوروغواي', 1, 1700, true),
  (nationality_list_id, 'VE', 'Vénézuélienne', 'فنزويلي', 1, 1710, true),
  (nationality_list_id, 'VN', 'Vietnamienne', 'فيتنامي', 1, 1720, true),
  (nationality_list_id, 'YE', 'Yéménite', 'يمني', 1, 1730, true),
  (nationality_list_id, 'ZM', 'Zambienne', 'زامبي', 1, 1740, true),
  (nationality_list_id, 'ZW', 'Zimbabwéenne', 'زيمبابوي', 1, 1750, true),
  (nationality_list_id, 'OTHER', 'Autre', 'أخرى', 1, 9999, true)
  ON CONFLICT (list_id, value_code) DO NOTHING;
END $$;