-- Créer la table des nationalités
CREATE TABLE public.nationalities (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  code TEXT NOT NULL UNIQUE,
  label_fr TEXT NOT NULL,
  label_ar TEXT,
  sort_order INTEGER DEFAULT 0,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- Enable Row Level Security
ALTER TABLE public.nationalities ENABLE ROW LEVEL SECURITY;

-- Politique pour la lecture (tout le monde peut lire)
CREATE POLICY "Tout le monde peut voir les nationalités"
ON public.nationalities
FOR SELECT
USING (is_active = true);

-- Politique pour la gestion (admins uniquement)
CREATE POLICY "Admins peuvent gérer les nationalités"
ON public.nationalities
FOR ALL
USING (is_admin_or_librarian(auth.uid()));

-- Créer un index pour les recherches
CREATE INDEX idx_nationalities_label_fr ON public.nationalities(label_fr);
CREATE INDEX idx_nationalities_code ON public.nationalities(code);

-- Insérer les nationalités principales (ordre alphabétique en français)
INSERT INTO public.nationalities (code, label_fr, sort_order) VALUES
('AF', 'Afghane', 10),
('ZA', 'Sud-Africaine', 20),
('AL', 'Albanaise', 30),
('DZ', 'Algérienne', 40),
('DE', 'Allemande', 50),
('US', 'Américaine', 60),
('AD', 'Andorrane', 70),
('AO', 'Angolaise', 80),
('SA', 'Saoudienne', 90),
('AR', 'Argentine', 100),
('AM', 'Arménienne', 110),
('AU', 'Australienne', 120),
('AT', 'Autrichienne', 130),
('AZ', 'Azerbaïdjanaise', 140),
('BS', 'Bahamienne', 150),
('BH', 'Bahreïnienne', 160),
('BD', 'Bangladaise', 170),
('BB', 'Barbadienne', 180),
('BE', 'Belge', 190),
('BZ', 'Bélizienne', 200),
('BJ', 'Béninoise', 210),
('BT', 'Bhoutanaise', 220),
('BY', 'Biélorusse', 230),
('BO', 'Bolivienne', 240),
('BA', 'Bosnienne', 250),
('BW', 'Botswanaise', 260),
('BR', 'Brésilienne', 270),
('BN', 'Brunéienne', 280),
('BG', 'Bulgare', 290),
('BF', 'Burkinabè', 300),
('BI', 'Burundaise', 310),
('KH', 'Cambodgienne', 320),
('CM', 'Camerounaise', 330),
('CA', 'Canadienne', 340),
('CV', 'Cap-verdienne', 350),
('CL', 'Chilienne', 360),
('CN', 'Chinoise', 370),
('CY', 'Chypriote', 380),
('CO', 'Colombienne', 390),
('KM', 'Comorienne', 400),
('CG', 'Congolaise', 410),
('CD', 'Congolaise (RDC)', 420),
('KR', 'Coréenne', 430),
('KP', 'Nord-Coréenne', 440),
('CR', 'Costaricienne', 450),
('CI', 'Ivoirienne', 460),
('HR', 'Croate', 470),
('CU', 'Cubaine', 480),
('DK', 'Danoise', 490),
('DJ', 'Djiboutienne', 500),
('DM', 'Dominiquaise', 510),
('EG', 'Égyptienne', 520),
('AE', 'Émiratie', 530),
('EC', 'Équatorienne', 540),
('ER', 'Érythréenne', 550),
('ES', 'Espagnole', 560),
('EE', 'Estonienne', 570),
('ET', 'Éthiopienne', 580),
('FJ', 'Fidjienne', 590),
('FI', 'Finlandaise', 600),
('FR', 'Française', 610),
('GA', 'Gabonaise', 620),
('GM', 'Gambienne', 630),
('GE', 'Géorgienne', 640),
('GH', 'Ghanéenne', 650),
('GR', 'Grecque', 660),
('GD', 'Grenadienne', 670),
('GT', 'Guatémaltèque', 680),
('GN', 'Guinéenne', 690),
('GQ', 'Équato-guinéenne', 700),
('GW', 'Bissau-guinéenne', 710),
('GY', 'Guyanienne', 720),
('HT', 'Haïtienne', 730),
('HN', 'Hondurienne', 740),
('HU', 'Hongroise', 750),
('IN', 'Indienne', 760),
('ID', 'Indonésienne', 770),
('IQ', 'Irakienne', 780),
('IR', 'Iranienne', 790),
('IE', 'Irlandaise', 800),
('IS', 'Islandaise', 810),
('IL', 'Israélienne', 820),
('IT', 'Italienne', 830),
('JM', 'Jamaïcaine', 840),
('JP', 'Japonaise', 850),
('JO', 'Jordanienne', 860),
('KZ', 'Kazakhe', 870),
('KE', 'Kényane', 880),
('KG', 'Kirghize', 890),
('KI', 'Kiribatienne', 900),
('KW', 'Koweïtienne', 910),
('LA', 'Laotienne', 920),
('LS', 'Lesothane', 930),
('LV', 'Lettone', 940),
('LB', 'Libanaise', 950),
('LR', 'Libérienne', 960),
('LY', 'Libyenne', 970),
('LI', 'Liechtensteinoise', 980),
('LT', 'Lituanienne', 990),
('LU', 'Luxembourgeoise', 1000),
('MK', 'Macédonienne', 1010),
('MG', 'Malgache', 1020),
('MY', 'Malaisienne', 1030),
('MW', 'Malawienne', 1040),
('MV', 'Maldivienne', 1050),
('ML', 'Malienne', 1060),
('MT', 'Maltaise', 1070),
('MA', 'Marocaine', 1080),
('MH', 'Marshallaise', 1090),
('MU', 'Mauricienne', 1100),
('MR', 'Mauritanienne', 1110),
('MX', 'Mexicaine', 1120),
('FM', 'Micronésienne', 1130),
('MD', 'Moldave', 1140),
('MC', 'Monégasque', 1150),
('MN', 'Mongole', 1160),
('ME', 'Monténégrine', 1170),
('MZ', 'Mozambicaine', 1180),
('MM', 'Birmane', 1190),
('NA', 'Namibienne', 1200),
('NR', 'Nauruane', 1210),
('NP', 'Népalaise', 1220),
('NI', 'Nicaraguayenne', 1230),
('NE', 'Nigérienne', 1240),
('NG', 'Nigériane', 1250),
('NO', 'Norvégienne', 1260),
('NZ', 'Néo-zélandaise', 1270),
('OM', 'Omanaise', 1280),
('UG', 'Ougandaise', 1290),
('UZ', 'Ouzbèke', 1300),
('PK', 'Pakistanaise', 1310),
('PW', 'Palaosienne', 1320),
('PA', 'Panaméenne', 1330),
('PG', 'Papouane-néo-guinéenne', 1340),
('PY', 'Paraguayenne', 1350),
('NL', 'Néerlandaise', 1360),
('PE', 'Péruvienne', 1370),
('PH', 'Philippine', 1380),
('PL', 'Polonaise', 1390),
('PT', 'Portugaise', 1400),
('QA', 'Qatarienne', 1410),
('RO', 'Roumaine', 1420),
('GB', 'Britannique', 1430),
('RU', 'Russe', 1440),
('RW', 'Rwandaise', 1450),
('KN', 'Kittitienne-et-névicienne', 1460),
('LC', 'Saint-lucienne', 1470),
('SM', 'Saint-marinaise', 1480),
('VC', 'Saint-vincentaise', 1490),
('SB', 'Salomonaise', 1500),
('SV', 'Salvadorienne', 1510),
('WS', 'Samoane', 1520),
('ST', 'Santoméenne', 1530),
('SN', 'Sénégalaise', 1540),
('RS', 'Serbe', 1550),
('SC', 'Seychelloise', 1560),
('SL', 'Sierra-léonaise', 1570),
('SG', 'Singapourienne', 1580),
('SK', 'Slovaque', 1590),
('SI', 'Slovène', 1600),
('SO', 'Somalienne', 1610),
('SD', 'Soudanaise', 1620),
('SS', 'Sud-soudanaise', 1630),
('LK', 'Sri-lankaise', 1640),
('SE', 'Suédoise', 1650),
('CH', 'Suisse', 1660),
('SR', 'Surinamaise', 1670),
('SZ', 'Swazie', 1680),
('SY', 'Syrienne', 1690),
('TJ', 'Tadjike', 1700),
('TZ', 'Tanzanienne', 1710),
('TD', 'Tchadienne', 1720),
('CZ', 'Tchèque', 1730),
('TH', 'Thaïlandaise', 1740),
('TL', 'Est-timoraise', 1750),
('TG', 'Togolaise', 1760),
('TO', 'Tongienne', 1770),
('TT', 'Trinidadienne', 1780),
('TN', 'Tunisienne', 1790),
('TM', 'Turkmène', 1800),
('TR', 'Turque', 1810),
('TV', 'Tuvaluane', 1820),
('UA', 'Ukrainienne', 1830),
('UY', 'Uruguayenne', 1840),
('VU', 'Vanuatuane', 1850),
('VA', 'Vaticane', 1860),
('VE', 'Vénézuélienne', 1870),
('VN', 'Vietnamienne', 1880),
('YE', 'Yéménite', 1890),
('ZM', 'Zambienne', 1900),
('ZW', 'Zimbabwéenne', 1910),
('OTHER', 'Autre', 9999);

-- Trigger pour mettre à jour updated_at
CREATE TRIGGER update_nationalities_updated_at
BEFORE UPDATE ON public.nationalities
FOR EACH ROW
EXECUTE FUNCTION public.update_updated_at_column();