-- Supprimer les listes système vides (anciennes listes non utilisées)
-- Ces listes ont été identifiées comme ayant 0 valeurs et ne sont plus utilisées dans l'application

DELETE FROM system_list_values
WHERE list_id IN (
  SELECT id FROM system_lists 
  WHERE list_code IN (
    'TYPE_NOTIFICATION',
    'PERMISSIONS',
    'ROLES_UTILISATEUR',
    'PRIORITE',
    'STATUT_GENERAL',
    'TYPE_DOCUMENT',
    'FORMAT_FICHIER',
    'NIVEAU_ACCES',
    'CATEGORIE_CONTENU',
    'TYPE_NOTICE_CBM',
    'STATUT_NOTICE',
    'REGIONS_MAROC',
    'STATUT_AUTEUR',
    'VILLES_MAROC',
    'TYPE_EDITEUR',
    'TYPE_IMPRIMEUR',
    'DISCIPLINES',
    'TYPE_SUPPORT',
    'NATURE_DECLARATION',
    'STATUT_DEMANDE',
    'ETAPE_WORKFLOW',
    'QUALITE_REPRODUCTION',
    'TYPE_REPRODUCTION',
    'STATUT_REPRODUCTION',
    'MODE_PAIEMENT',
    'STATUT_PAIEMENT',
    'TYPE_SERVICE_BNRM',
    'TARIF_CATEGORIE',
    'LANGUE_MANUSCRIT',
    'GENRE_MANUSCRIT',
    'SCRIPT_MANUSCRIT',
    'ETAT_CONSERVATION',
    'MATERIAU_MANUSCRIT',
    'PERIODE_MANUSCRIT'
  )
);

-- Supprimer les listes vides
DELETE FROM system_lists 
WHERE list_code IN (
  'TYPE_NOTIFICATION',
  'PERMISSIONS',
  'ROLES_UTILISATEUR',
  'PRIORITE',
  'STATUT_GENERAL',
  'TYPE_DOCUMENT',
  'FORMAT_FICHIER',
  'NIVEAU_ACCES',
  'CATEGORIE_CONTENU',
  'TYPE_NOTICE_CBM',
  'STATUT_NOTICE',
  'REGIONS_MAROC',
  'STATUT_AUTEUR',
  'VILLES_MAROC',
  'TYPE_EDITEUR',
  'TYPE_IMPRIMEUR',
  'DISCIPLINES',
  'TYPE_SUPPORT',
  'NATURE_DECLARATION',
  'STATUT_DEMANDE',
  'ETAPE_WORKFLOW',
  'QUALITE_REPRODUCTION',
  'TYPE_REPRODUCTION',
  'STATUT_REPRODUCTION',
  'MODE_PAIEMENT',
  'STATUT_PAIEMENT',
  'TYPE_SERVICE_BNRM',
  'TARIF_CATEGORIE',
  'LANGUE_MANUSCRIT',
  'GENRE_MANUSCRIT',
  'SCRIPT_MANUSCRIT',
  'ETAT_CONSERVATION',
  'MATERIAU_MANUSCRIT',
  'PERIODE_MANUSCRIT'
);