-- Insert example documents for testing with correct content_type enum values
INSERT INTO content (
  id, 
  title, 
  slug,
  excerpt,
  content_body, 
  content_type, 
  status,
  author_id,
  published_at,
  tags,
  download_enabled,
  file_url,
  file_type,
  featured_image_url
)
VALUES
  (
    '550e8400-e29b-41d4-a716-446655440001',
    'Histoire du Maroc contemporain',
    'histoire-du-maroc-contemporain',
    'Une exploration approfondie de l''histoire moderne du Maroc',
    'Une exploration approfondie de l''histoire moderne du Maroc, de la période coloniale à nos jours. Cet ouvrage examine les transformations politiques, sociales et économiques qui ont façonné le Maroc contemporain. Ce document n''est pas encore numérisé.',
    'news',
    'published',
    '5631cc25-129d-4635-bbf3-a9eb8443f6a4',
    '2023-06-15 00:00:00+00',
    ARRAY['Histoire', 'Maroc', 'Politique'],
    false,
    NULL,
    'PDF',
    NULL
  ),
  (
    '550e8400-e29b-41d4-a716-446655440002',
    'Manuscrit andalou rare - XIIe siècle',
    'manuscrit-andalou-rare-xiie-siecle',
    'Manuscrit andalou exceptionnel datant du XIIe siècle',
    'Manuscrit andalou exceptionnel datant du XIIe siècle, contenant des textes philosophiques et poétiques de l''époque almohade. Ce document précieux témoigne de l''âge d''or de la civilisation andalouse. Document non numérisé nécessitant une demande.',
    'exhibition',
    'published',
    '5631cc25-129d-4635-bbf3-a9eb8443f6a4',
    '2024-01-10 00:00:00+00',
    ARRAY['Philosophie', 'Poésie', 'Andalousie'],
    false,
    NULL,
    'Manuscrit',
    NULL
  ),
  (
    '550e8400-e29b-41d4-a716-446655440003',
    'Archives photographiques de Rabat',
    'archives-photographiques-de-rabat',
    'Collection exceptionnelle de photographies historiques de Rabat',
    'Collection exceptionnelle de photographies historiques de Rabat capturant l''évolution de la capitale marocaine depuis le début du XXe siècle. Images noir et blanc de grande qualité documentant l''architecture, les événements et la vie quotidienne. Non numérisé.',
    'news',
    'published',
    '5631cc25-129d-4635-bbf3-a9eb8443f6a4',
    '2024-02-20 00:00:00+00',
    ARRAY['Photographie', 'Rabat', 'Architecture', 'Histoire'],
    false,
    NULL,
    'Photographie',
    NULL
  ),
  (
    '550e8400-e29b-41d4-a716-446655440004',
    'La littérature marocaine d''expression française',
    'la-litterature-marocaine-expression-francaise',
    'Étude critique de la littérature marocaine francophone',
    'Étude critique de la littérature marocaine francophone, explorant les thèmes identitaires, culturels et sociaux dans les œuvres des grands auteurs marocains. Analyse approfondie des courants littéraires et de leur évolution.',
    'news',
    'published',
    '5631cc25-129d-4635-bbf3-a9eb8443f6a4',
    '2022-03-10 00:00:00+00',
    ARRAY['Littérature', 'Francophonie', 'Maroc', 'Culture'],
    true,
    NULL,
    'PDF',
    NULL
  ),
  (
    '550e8400-e29b-41d4-a716-446655440005',
    'Recueil de poésie amazighe traditionnelle',
    'recueil-de-poesie-amazighe-traditionnelle',
    'Anthologie de poésies amazighes traditionnelles',
    'Anthologie de poésies amazighes traditionnelles des différentes régions du Maroc. Ces textes oraux transmis de génération en génération ont été transcrits et traduits pour préserver ce patrimoine culturel immatériel.',
    'news',
    'published',
    '5631cc25-129d-4635-bbf3-a9eb8443f6a4',
    '2023-09-05 00:00:00+00',
    ARRAY['Poésie', 'Amazigh', 'Tradition orale', 'Culture'],
    false,
    NULL,
    'PDF',
    NULL
  )
ON CONFLICT (id) DO UPDATE
SET 
  title = EXCLUDED.title,
  slug = EXCLUDED.slug,
  excerpt = EXCLUDED.excerpt,
  content_body = EXCLUDED.content_body,
  content_type = EXCLUDED.content_type,
  status = EXCLUDED.status,
  published_at = EXCLUDED.published_at,
  tags = EXCLUDED.tags,
  download_enabled = EXCLUDED.download_enabled,
  file_type = EXCLUDED.file_type;